import type { PaperManifest, PaperQuestion, PaperResource } from "../../src/papers.ts";
import { choiceQuestion, essayQuestion, inkQuestion, samplePaper, shortQuestion, textResource } from "./helpers.ts";

function mathematicsSamples(
  subject: string,
  subjectLabel: string,
  paperOneInstructions: string,
  paperOneQuestions: PaperQuestion[],
  paperTwoQuestions: PaperQuestion[],
  paperOneResources: PaperResource[] = [],
  paperTwoResources: PaperResource[] = [],
): PaperManifest[] {
  return [
    samplePaper({
      subject,
      subjectLabel,
      level: "SL",
      paper: "Paper 1 (SL) — original full-format practice",
      durationMinutes: 90,
      readingTimeMinutes: 5,
      maximumMarks: 80,
      mode: "reading",
      instructions: paperOneInstructions,
      selectionMode: "all",
      resources: paperOneResources,
      questions: paperOneQuestions,
    }),
    samplePaper({
      subject,
      subjectLabel,
      level: "HL",
      paper: "Paper 2 (HL) — original full-format practice",
      durationMinutes: 120,
      readingTimeMinutes: 5,
      maximumMarks: 110,
      mode: "reading",
      instructions: "An approved graphing calculator is required. Answer every question in its linked digital working area, preserving intermediate steps, units and graphs. No separate answer sheet is used.",
      selectionMode: "all",
      resources: paperTwoResources,
      questions: paperTwoQuestions,
    }),
  ];
}

const mathematicsAA = mathematicsSamples(
  "mathematics-analysis-approaches",
  "Mathematics: Analysis and Approaches",
  "Do not use a calculator. Answer every question in its digital working area, show all reasoning, and give exact values where requested. No separate answer sheet is used.",
  [
    inkQuestion("q1", "Question 1 — algebra", "Factorize 2x² − 7x + 3, and hence solve 2x² − 7x + 3 = 0.", 5),
    inkQuestion("q2", "Question 2 — sequences", "An arithmetic sequence has fifth term 18 and twelfth term 46. Find the first term and common difference, then determine the sum of the first 20 terms.", 6),
    inkQuestion("q3", "Question 3 — calculus", "For f(x) = x³ − 3x² − 9x + 5, find the coordinates of both stationary points and classify each one.", 7),
    inkQuestion("q4", "Question 4 — trigonometry", "Given that sin θ = 3/5 and π/2 < θ < π, find the exact values of cos θ and sin(2θ).", 4),
    inkQuestion("q5", "Question 5 — logarithms", "Solve exactly log₂(x − 1) + log₂(x + 2) = 3, stating any rejected value.", 6),
    inkQuestion("q6", "Question 6 — binomial theorem", "Find the coefficient of x³ in the expansion of (2 − x)⁶ and use the first four terms to approximate 1.99⁶.", 6),
    inkQuestion("q7", "Question 7 — probability", "Events A and B satisfy P(A) = 0.62, P(B) = 0.45 and P(A ∪ B) = 0.79. Find P(A ∩ B), P(A | B), and determine whether A and B are independent.", 7),
    inkQuestion("q8", "Question 8 — coordinate geometry", "The line 3x − 2y + 7 = 0 is tangent to a circle at P(1, 5). Find the equation of the circle if its centre lies on x + y = 2.", 7),
    inkQuestion("q9", "Question 9 — functions", "Let f(x) = |2x − 3| − 1. Sketch y = f(x), solve f(x) = 2, and state the range of f.", 8, [], 2),
    inkQuestion("q10", "Question 10 — differentiation", "A rectangular sheet 24 cm by 16 cm has squares of side x removed from each corner and is folded into an open box. Find the value of x that maximizes the volume and justify that it is a maximum.", 8, [], 2),
    inkQuestion("q11", "Question 11 — proof", "Prove by mathematical induction that 1·2 + 2·3 + ··· + n(n + 1) = n(n + 1)(n + 2)/3 for every positive integer n.", 8, [], 2),
    inkQuestion("q12", "Question 12 — trigonometric modelling", "The depth d metres of water at a harbour is modelled by d(t) = 5.2 + 1.8 cos(πt/6), where t is hours after midnight. Find the first two times when d = 4.3 and the total time in the first 12 hours for which d is below 4.3.", 8, [], 2),
  ],
  [
    inkQuestion("q1", "Question 1 — functions", "The function f(x) = (2x + 1)/(x − 3). Find f⁻¹(x), state the domain of f⁻¹, and solve f(f(x)) = x.", 7),
    inkQuestion("q2", "Question 2 — integration", "The curve y = x e^(−x) meets the x-axis at the origin. Find the exact area under the curve from x = 0 to x = 3, then give a decimal answer to three significant figures.", 7),
    inkQuestion("q3", "Question 3 — vectors", "Points A(1, −2, 3), B(5, 0, −1) and C(3, 4, 2) define a triangle. Find its area and the angle ABC.", 8, [], 2),
    inkQuestion("q4", "Question 4 — probability", "A biased coin has P(heads) = p. In 12 independent tosses, the probability of exactly 7 heads is 0.158 to three decimal places. Determine all possible values of p and explain which is more plausible if 80 heads were observed in 120 earlier tosses.", 8, [], 2),
    inkQuestion("q5", "Question 5 — complex numbers", "The complex number z satisfies z³ = 8(cos(2π/3) + i sin(2π/3)). Find the three roots in modulus-argument form and represent them on an Argand diagram.", 10, [], 2),
    inkQuestion("q6", "Question 6 — differential equations", "Solve dy/dx = (x + 1)(y − 2), given y(0) = 3. Hence determine the value of x > 0 for which y = 5.", 10, [], 2),
    inkQuestion("q7", "Question 7 — distributions", "The mass of a product is normally distributed with mean μ and standard deviation 1.8 g. It is known that 8% weigh less than 96 g and 3% weigh more than 103 g. Determine μ and comment on the consistency of the two statements.", 10, [], 2),
    inkQuestion("q8", "Question 8 — series", "A power series has general term (−1)ⁿx^(2n+1)/(2n+1). Determine its radius and interval of convergence, and use four non-zero terms to estimate the integral of 1/(1+x²) from 0 to 1/2 with an error bound.", 10, [], 2),
    inkQuestion("q9", "Question 9 — vector geometry", "Lines l₁ and l₂ are r = (1,2,−1) + λ(2,−1,3) and r = (4,0,5) + μ(1,2,−1). Determine whether they intersect. If not, find their shortest distance.", 10, [], 2),
    inkQuestion("q10", "Question 10 — numerical integration", "For f(x) = ln(1 + x²), use technology to find the zeros of f(x) − x/2 and the enclosed area. Explain how the graph confirms the limits used.", 10, [], 2),
    inkQuestion("q11", "Question 11 — hypothesis testing", "A machine should fill 500 ml bottles. A random sample of 20 has mean 497.8 ml and standard deviation 4.6 ml. At the 5% level, test whether the machine is underfilling, state assumptions, and interpret the p-value.", 10, [], 2),
    inkQuestion("q12", "Question 12 — optimization", "A point P moves on y = e^(−x²), x ≥ 0. Find numerically the position of P for which the rectangle with vertices (0,0), (x,0), P and (0,y) has maximum area. Give a calculus justification.", 10, [], 2),
  ],
);

const aiDataOne = textResource(
  "commute-data",
  "Original data set — commute and study time",
  "Six students recorded daily commute time x (minutes) and evening study time y (minutes):\nA: 12, 94\nB: 18, 86\nC: 25, 82\nD: 33, 69\nE: 41, 63\nF: 55, 48",
);
const aiDataTwo = textResource(
  "energy-data",
  "Original data set — energy demand",
  "A campus recorded mean outdoor temperature T (°C) and daily electricity demand E (MWh):\nT: 4, 7, 10, 13, 16, 19, 22, 25\nE: 31.2, 28.1, 25.4, 23.0, 21.9, 22.5, 25.1, 29.8",
);

const mathematicsAI = mathematicsSamples(
  "mathematics-applications-interpretation",
  "Mathematics: Applications and Interpretation",
  "An approved graphing calculator is required. Answer every question in its digital working area, preserving intermediate steps, units and graphs. No separate answer sheet is used.",
  [
    inkQuestion("q1", "Question 1 — finance", "A student deposits 6000 yuan in an account paying 3.2% annual interest compounded monthly. Find the balance after 4 years and the first month in which the balance exceeds 7000 yuan.", 6),
    inkQuestion("q2", "Question 2 — statistics", "Use the commute data to find Pearson’s correlation coefficient and the least-squares regression line of y on x. Interpret the slope in context.", 7, ["commute-data"], 2),
    inkQuestion("q3", "Question 3 — modelling", "A water tank initially contains 1200 L and drains at a rate modelled by V(t) = 1200(0.93)^t, where t is measured in minutes. Find the volume after 15 minutes and the time at which 75% of the original water has drained.", 6),
    inkQuestion("q4", "Question 4 — geometry", "A wheelchair ramp rises 0.84 m over a horizontal distance of 10.5 m. Calculate its angle of elevation and its length. A guideline limits the angle to 5°. Decide whether the ramp satisfies the guideline.", 5),
    inkQuestion("q5", "Question 5 — networks", "A delivery network has vertices A, B, C, D and E with edge weights AB 7, AC 4, BC 3, BD 6, CD 5, CE 8 and DE 2. Use Kruskal's algorithm to find a minimum spanning tree and its total weight.", 8, [], 2),
    inkQuestion("q6", "Question 6 — probability distributions", "The number of customers arriving in ten minutes follows a Poisson distribution with mean 3.4. Find the probability of at least five arrivals and the smallest number n such that P(X ≤ n) > 0.95.", 8),
    inkQuestion("q7", "Question 7 — sinusoidal modelling", "A daylight model is D(t) = a sin(b(t − c)) + d hours. Given a maximum of 15.2 hours at day 172 and a minimum of 8.8 hours at day 355, determine a, b, c and d and estimate D(80).", 8, [], 2),
    inkQuestion("q8", "Question 8 — Voronoi diagram", "Three emergency stations are at A(1,2), B(9,2) and C(5,8). Find equations of the perpendicular bisectors and determine the region closest to C. Decide which station serves P(4,4).", 8, [], 2),
    inkQuestion("q9", "Question 9 — numerical methods", "Use technology to solve 2e^(−0.3x) = 0.2x + 0.5. Explain the meaning of each intersection if the two sides model supply and demand in hundreds of units.", 8),
    inkQuestion("q10", "Question 10 — bivariate statistics", "A regression model y = 1.72x + 14.6 has r = 0.81 for x between 10 and 40. Estimate y at x = 32, explain the meaning of r², and evaluate using the model at x = 75.", 8),
    inkQuestion("q11", "Question 11 — calculus with technology", "The profit from selling x hundred tickets is P(x) = −2.4x³ + 18x² + 12x − 40. Find all stationary points in 0 ≤ x ≤ 8 and determine the ticket quantity giving maximum profit.", 8, [], 2),
  ],
  [
    inkQuestion("q1", "Question 1 — nonlinear regression", "Use the energy-demand data to compare a linear model with a quadratic model. State suitable equations, compare their fit, and use the better model to estimate demand at 28°C. Comment on the reliability of the estimate.", 9, ["energy-data"], 2),
    inkQuestion("q2", "Question 2 — transition matrices", "A bike-share survey classifies users as occasional (O) or regular (R). Each month, 35% of O users become R and 15% of R users become O. Starting with 800 O users and 200 R users, construct a transition matrix, find the distribution after six months, and determine the long-term distribution.", 9, [], 2),
    inkQuestion("q3", "Question 3 — hypothesis testing", "A school claims that the median queue time in its cafeteria is 6 minutes. A random sample of 14 queue times is 4.1, 5.0, 5.2, 5.6, 5.8, 6.1, 6.3, 6.7, 7.0, 7.2, 7.8, 8.1, 9.0, 10.4. Perform a suitable test at the 5% level and state your conclusion in context.", 8, [], 2),
    inkQuestion("q4", "Question 4 — differential modelling", "The rate of change of an algae population P is modelled by dP/dt = 0.18P(1 − P/5000). Given P(0) = 400, use technology to estimate P(20), find when P first exceeds 4000, and explain the meaning of 5000 in the model.", 8, [], 2),
    inkQuestion("q5", "Question 5 — chi-squared test", "A survey records transport choice for 120 students by year group. Construct an appropriate contingency table from the supplied totals, perform a chi-squared test for independence at 5%, and state a contextual conclusion.", 9, [], 2),
    inkQuestion("q6", "Question 6 — graph theory", "A weighted graph models inspection routes between six sites. Use a nearest-neighbour upper bound and a deleted-vertex lower bound to propose a tour, then calculate the percentage gap between the bounds.", 9, [], 2),
    inkQuestion("q7", "Question 7 — differential equations", "A medicine concentration satisfies dC/dt = 12 − 0.25C with C(0)=0. Solve the equation, identify the limiting concentration, and find when the concentration first reaches 40 mg L⁻¹.", 9, [], 2),
    inkQuestion("q8", "Question 8 — optimization", "A manufacturer models unit cost by C(x) = 1800/x + 0.04x + 12 for 20 ≤ x ≤ 400. Find the output minimizing cost and perform a sensitivity check if the fixed-cost term changes by 10%.", 9, [], 2),
    inkQuestion("q9", "Question 9 — time series", "Quarterly sales show a linear trend with additive seasonal effects. Using the supplied eight-quarter pattern, calculate four-point moving averages, estimate seasonal components and forecast the next two quarters.", 10, [], 2),
    inkQuestion("q10", "Question 10 — inference", "Two independent samples compare battery life. Use technology to construct a 95% confidence interval for the difference in population means, test the manufacturer's claim, and state two assumptions.", 10, [], 2),
    inkQuestion("q11", "Question 11 — matrices", "A three-state migration model is represented by a stochastic matrix. Determine its stationary distribution, calculate the population after ten transitions, and explain one limitation of the Markov assumption.", 10, [], 2),
    inkQuestion("q12", "Question 12 — coupled modelling", "Build a piecewise model for a reservoir receiving seasonal inflow and constant demand. Use a spreadsheet or graphing technology to identify the first month storage falls below 20% and evaluate one demand-management proposal.", 10, [], 2),
  ],
  [aiDataOne],
  [aiDataTwo],
);

interface ScienceConfig {
  subject: string;
  label: string;
  materialsInstructions: string;
  paperOneResources: PaperResource[];
  paperOneQuestions: PaperQuestion[];
  paperTwoResources: PaperResource[];
  paperTwoQuestions: PaperQuestion[];
}

function scienceSamples(config: ScienceConfig): PaperManifest[] {
  return [
    samplePaper({
      subject: config.subject,
      subjectLabel: config.label,
      level: "SL",
      paper: "Paper 1 (SL) — original full-format practice",
      durationMinutes: 90,
      readingTimeMinutes: 5,
      maximumMarks: config.paperOneQuestions.reduce((sum, question) => sum + (question.marks ?? 0), 0),
      mode: "reading",
      instructions: `Complete the selected-response and data/working questions under one timer. ${config.materialsInstructions} Enter each answer beside its question; no separate answer sheet is used.`,
      selectionMode: "all",
      resources: config.paperOneResources,
      questions: config.paperOneQuestions,
    }),
    samplePaper({
      subject: config.subject,
      subjectLabel: config.label,
      level: "HL",
      paper: "Paper 2 (HL) — original full-format practice",
      durationMinutes: 150,
      readingTimeMinutes: 5,
      maximumMarks: config.paperTwoQuestions.reduce((sum, question) => sum + (question.marks ?? 0), 0),
      mode: "reading",
      instructions: `Answer every question using the response area attached to it. ${config.materialsInstructions} Show calculations, units, diagrams and reasoning where required. No separate answer sheet is used.`,
      selectionMode: "all",
      resources: config.paperTwoResources,
      questions: config.paperTwoQuestions,
    }),
  ];
}

const biology = scienceSamples({
  subject: "biology",
  label: "Biology",
  materialsInstructions: "An approved calculator is required; all data needed for this original sample is supplied within DigitalDP.",
  paperOneResources: [textResource("enzyme-data", "Original enzyme data", "Temperature (°C): 10, 20, 30, 40, 50\nMean product formed in 5 min (mg): 1.2, 2.7, 5.4, 7.1, 2.3")],
  paperOneQuestions: [
    choiceQuestion("q1", "Paper 1A · Question 1", "Which structure is present in both prokaryotic and eukaryotic cells?", ["Nucleus", "Mitochondrion", "Ribosome", "Golgi apparatus"], 1),
    choiceQuestion("q2", "Paper 1A · Question 2", "Which process directly increases genetic variation during meiosis?", ["Binary fission", "Crossing over", "DNA translation", "Cytokinesis"], 1),
    choiceQuestion("q3", "Paper 1A · Question 3", "Which relationship describes energy transfer between trophic levels?", ["Energy is recycled completely", "Energy increases at each level", "Some energy is lost as heat", "Only producers respire"], 1),
    choiceQuestion("q4", "Paper 1A · Question 4", "A competitive inhibitor most directly affects which feature of an enzyme?", ["Its amino-acid sequence", "Its active-site availability", "Its gene location", "Its product mass"], 1),
    choiceQuestion("q5", "Paper 1A · Question 5", "Which molecule is the immediate source of energy for active transport?", ["DNA", "ATP", "Oxygen", "Glucose"], 1),
    choiceQuestion("q6", "Paper 1A · Question 6", "Which feature increases the surface area of an absorptive epithelial cell?", ["Centrioles", "Microvilli", "Chromatin", "Lysosomes"], 1),
    choiceQuestion("q7", "Paper 1A · Question 7", "During which part of the cell cycle is DNA replicated?", ["G1", "S", "G2", "M"], 1),
    choiceQuestion("q8", "Paper 1A · Question 8", "Which bond joins adjacent amino acids in a polypeptide?", ["Glycosidic", "Peptide", "Hydrogen", "Phosphodiester"], 1),
    choiceQuestion("q9", "Paper 1A · Question 9", "Which process produces mRNA from a DNA template?", ["Translation", "Replication", "Transcription", "Translocation"], 1),
    choiceQuestion("q10", "Paper 1A · Question 10", "Which event occurs at a ribosome?", ["DNA unwinds", "Codons pair with anticodons", "Introns replicate", "Lipids polymerize"], 1),
    choiceQuestion("q11", "Paper 1A · Question 11", "What is the primary function of xylem vessels?", ["Transport sugars", "Transport water and ions", "Control gas exchange", "Store genetic information"], 1),
    choiceQuestion("q12", "Paper 1A · Question 12", "Which change tends to close stomata?", ["High guard-cell turgor", "Water loss from guard cells", "Blue light", "Low internal carbon dioxide"], 1),
    choiceQuestion("q13", "Paper 1A · Question 13", "Which hormone lowers blood glucose concentration?", ["Glucagon", "Insulin", "Adrenaline", "Thyroxine"], 1),
    choiceQuestion("q14", "Paper 1A · Question 14", "Which structure prevents backflow in the heart?", ["Valve", "Septum", "Atrium", "Pacemaker"], 1),
    choiceQuestion("q15", "Paper 1A · Question 15", "Which immune cell secretes antibodies?", ["Platelet", "Plasma cell", "Phagocyte", "Erythrocyte"], 1),
    choiceQuestion("q16", "Paper 1A · Question 16", "What is the role of a myelin sheath?", ["Produce neurotransmitter", "Increase impulse conduction speed", "Connect muscles to bones", "Detect light"], 1),
    choiceQuestion("q17", "Paper 1A · Question 17", "Which statement describes negative feedback?", ["A change amplifies itself", "A response counteracts a deviation", "A mutation enters a population", "A stimulus is ignored"], 1),
    choiceQuestion("q18", "Paper 1A · Question 18", "Which gas is fixed during the Calvin cycle?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Methane"], 1),
    choiceQuestion("q19", "Paper 1A · Question 19", "Where does oxidative phosphorylation occur in a eukaryotic cell?", ["Golgi apparatus", "Inner mitochondrial membrane", "Nucleolus", "Cell wall"], 1),
    choiceQuestion("q20", "Paper 1A · Question 20", "Which ecological term describes all populations living together in an area?", ["Community", "Habitat", "Species", "Biome"], 1),
    choiceQuestion("q21", "Paper 1A · Question 21", "What is measured by species richness?", ["Number of species", "Biomass of one species", "Rate of mutation", "Area of a habitat"], 1),
    choiceQuestion("q22", "Paper 1A · Question 22", "Which process can change allele frequencies by chance most strongly in a small population?", ["Gene expression", "Genetic drift", "Translation", "Homeostasis"], 1),
    choiceQuestion("q23", "Paper 1A · Question 23", "What does a cladogram represent?", ["Metabolic rate", "Hypothesized evolutionary relationships", "Daily population size", "Protein concentration"], 1),
    choiceQuestion("q24", "Paper 1A · Question 24", "Which condition is required for natural selection?", ["No heritable variation", "Differential reproductive success", "Identical environments", "No competition"], 1),
    choiceQuestion("q25", "Paper 1A · Question 25", "Which technique separates DNA fragments primarily by size?", ["Gel electrophoresis", "Chromatography", "Titration", "Centrifugation only"], 1),
    choiceQuestion("q26", "Paper 1A · Question 26", "What is the purpose of a control group?", ["Increase the dependent variable", "Provide a comparison without the tested treatment", "Remove replication", "Guarantee the hypothesis"], 1),
    choiceQuestion("q27", "Paper 1A · Question 27", "Which value best describes a strong negative correlation?", ["−0.92", "−0.08", "+0.08", "+0.92"], 1),
    choiceQuestion("q28", "Paper 1A · Question 28", "Which sampling method uses points at regular distances along a line?", ["Quadrat only", "Transect", "Capture–mark–recapture", "Pedigree"], 1),
    choiceQuestion("q29", "Paper 1A · Question 29", "Which observation is evidence of osmosis?", ["Solute crosses a metal wire", "Water moves across a partially permeable membrane", "ATP is hydrolysed", "A protein is translated"], 1),
    choiceQuestion("q30", "Paper 1A · Question 30", "Why are repeated measurements useful?", ["They remove all systematic error", "They permit assessment of variability", "They change the independent variable", "They prove causation"], 1),
    inkQuestion("q31", "Paper 1B · Data question 1", "Plot the enzyme data on suitable axes, describe the pattern, and identify the optimum temperature in this investigation.", 6, ["enzyme-data"], 2, "square-grid"),
    shortQuestion("q32", "Paper 1B · Data question 2", "Explain the change in product formation between 30°C and 50°C, referring to collision frequency and molecular structure.", 6, ["enzyme-data"]),
    essayQuestion("q33", "Paper 1B · Data question 3", "Design a controlled investigation to determine how pH affects the same enzyme. Include the independent and dependent variables, at least three controls, replication, uncertainty and a suitable display of results.", 6, ["enzyme-data"]),
    shortQuestion("q34", "Paper 1B · Data question 4", "A second group obtains means of 1.1, 2.9, 5.0, 6.8 and 4.9 mg at the same temperatures. Compare the results, identify one anomalous relationship, and evaluate whether the two data sets support the same conclusion.", 7, ["enzyme-data"]),
  ],
  paperTwoResources: [textResource("pond-study", "Original pond study", "Researchers added equal masses of leaf litter to eight pond tanks. Four tanks received extra nitrate. After 21 days, mean algal dry mass was 3.8 g without nitrate and 9.6 g with nitrate. Mean dissolved oxygen at dawn was 7.2 mg L⁻¹ without nitrate and 3.9 mg L⁻¹ with nitrate.")],
  paperTwoQuestions: [
    shortQuestion("q1", "Question 1 — data interpretation", "Calculate the percentage increase in mean algal dry mass caused by nitrate. Show the calculation and state the answer to three significant figures.", 5, ["pond-study"]),
    inkQuestion("q2", "Question 2 — causal model", "Construct an annotated causal diagram linking added nitrate to the change in dissolved oxygen at dawn.", 6, ["pond-study"], 1, "blank"),
    essayQuestion("q3", "Question 3 — experimental design", "Design a follow-up investigation to test whether light intensity changes the effect of nitrate on algal growth. Include variables, controls, replication and the data to be collected.", 8, ["pond-study"]),
    shortQuestion("q4", "Section A · Question 4 — membranes", "Explain how the properties of phospholipids and membrane proteins permit selective transport, using one passive and one active example.", 7),
    shortQuestion("q5", "Section A · Question 5 — genetics", "A heterozygous individual for two unlinked genes is test-crossed. Construct the cross, predict the phenotypic ratio, and explain how linkage would alter the result.", 6),
    shortQuestion("q6", "Section A · Question 6 — photosynthesis", "Outline how light energy is converted into chemical energy and used to produce carbohydrate. Distinguish events at the thylakoid from those in the stroma.", 6),
    shortQuestion("q7", "Section A · Question 7 — homeostasis", "Explain how insulin and glucagon coordinate the response to a meal and a subsequent period without food.", 5),
    shortQuestion("q8", "Section A · Question 8 — evolution", "Use natural selection to explain how resistance to a new antibiotic can become common in a bacterial population.", 5),
    essayQuestion("q9", "Section B · choose two alternatives", "Answer any two alternatives, writing a separate response for each.\nA. Explain how gene expression is regulated and how cell differentiation can arise from a shared genome. [16]\nB. Compare energy transfer and nutrient cycling in ecosystems, and evaluate one human intervention intended to improve sustainability. [16]\nC. Explain how nervous and hormonal communication coordinate responses in mammals. [16]", 32),
  ],
});

const chemistry = scienceSamples({
  subject: "chemistry",
  label: "Chemistry",
  materialsInstructions: "An approved calculator is required. Use the original reference data supplied within this sample; no external data booklet is needed.",
  paperOneResources: [textResource("chem-reference", "Reference data for this sample", "Relative atomic masses: H 1.01, C 12.01, O 16.00, Na 22.99, Mg 24.31, Cl 35.45\nSpecific heat capacity of water: 4.18 J g⁻¹ K⁻¹")],
  paperOneQuestions: [
    choiceQuestion("q1", "Paper 1A · Question 1", "What is the amount of substance in 4.00 g of sodium hydroxide, NaOH?", ["0.0500 mol", "0.100 mol", "0.200 mol", "1.00 mol"], 1, ["chem-reference"]),
    choiceQuestion("q2", "Paper 1A · Question 2", "Which species has a trigonal planar electron-domain geometry?", ["CH₄", "NH₃", "BF₃", "H₂O"], 1),
    choiceQuestion("q3", "Paper 1A · Question 3", "Which change always increases the rate constant for an elementary reaction?", ["Higher concentration", "Higher temperature", "Larger volume", "Lower pressure"], 1),
    choiceQuestion("q4", "Paper 1A · Question 4", "Which statement describes oxidation?", ["Gain of electrons", "Decrease in oxidation state", "Loss of electrons", "Gain of neutrons"], 1),
    choiceQuestion("q5", "Paper 1A · Question 5", "Which isotope notation represents an atom with 17 protons and 18 neutrons?", ["³⁵₁₇X", "¹⁸₁₇X", "³⁵₁₈X", "¹⁷₃₅X"], 1),
    choiceQuestion("q6", "Paper 1A · Question 6", "Which species has the smallest radius?", ["Na", "Na⁺", "Mg", "Mg²⁺"], 1),
    choiceQuestion("q7", "Paper 1A · Question 7", "Which bond is most polar?", ["H–F", "H–Cl", "H–Br", "H–I"], 1),
    choiceQuestion("q8", "Paper 1A · Question 8", "What is the molecular geometry of ammonia?", ["Linear", "Trigonal planar", "Trigonal pyramidal", "Tetrahedral"], 1),
    choiceQuestion("q9", "Paper 1A · Question 9", "Which intermolecular force acts between all molecular substances?", ["Hydrogen bonding", "Ion–dipole attraction", "London dispersion", "Metallic bonding"], 1),
    choiceQuestion("q10", "Paper 1A · Question 10", "Which sample contains the greatest number of molecules?", ["1 g H₂", "1 g O₂", "1 g N₂", "1 g CO₂"], 1),
    choiceQuestion("q11", "Paper 1A · Question 11", "Which expression gives concentration in mol dm⁻³?", ["mass × volume", "amount ÷ volume", "volume ÷ amount", "mass ÷ molar mass only"], 1),
    choiceQuestion("q12", "Paper 1A · Question 12", "For an exothermic reaction, which sign does ΔH have?", ["Positive", "Negative", "Always zero", "Undefined"], 1),
    choiceQuestion("q13", "Paper 1A · Question 13", "Which change raises the temperature of the surroundings most directly?", ["An endothermic process", "An exothermic process", "Melting", "Bond breaking alone"], 1),
    choiceQuestion("q14", "Paper 1A · Question 14", "At dynamic equilibrium, what is equal?", ["Reactant and product concentrations", "Forward and reverse rates", "All stoichiometric coefficients", "Activation energies"], 1),
    choiceQuestion("q15", "Paper 1A · Question 15", "Which change shifts a gaseous equilibrium toward the side with fewer gas particles?", ["Lower pressure", "Higher pressure", "A catalyst", "Greater surface area"], 1),
    choiceQuestion("q16", "Paper 1A · Question 16", "Which solution is acidic at 298 K?", ["pH 3", "pH 7", "pH 9", "pH 12"], 1),
    choiceQuestion("q17", "Paper 1A · Question 17", "Which pair can form a buffer?", ["Strong acid and strong base", "Weak acid and its conjugate base", "Two salts with no common ion", "Pure water and ethanol"], 1),
    choiceQuestion("q18", "Paper 1A · Question 18", "What is reduced in Zn + Cu²⁺ → Zn²⁺ + Cu?", ["Zn", "Cu²⁺", "Zn²⁺", "Neither species"], 1),
    choiceQuestion("q19", "Paper 1A · Question 19", "At the cathode of an electrolytic cell, which process occurs?", ["Oxidation", "Reduction", "Neutralization", "Combustion"], 1),
    choiceQuestion("q20", "Paper 1A · Question 20", "Which hydrocarbon is unsaturated?", ["Ethane", "Propane", "Ethene", "Methane"], 1),
    choiceQuestion("q21", "Paper 1A · Question 21", "Which reagent distinguishes an alkene from an alkane?", ["Bromine water", "Sodium chloride", "Universal indicator only", "Distilled water"], 1),
    choiceQuestion("q22", "Paper 1A · Question 22", "What is the functional group in an ester?", ["–OH", "–COO–", "–CHO", "–NH₂"], 1),
    choiceQuestion("q23", "Paper 1A · Question 23", "Which polymerization joins alkene monomers without a small-molecule by-product?", ["Condensation", "Addition", "Hydrolysis", "Substitution"], 1),
    choiceQuestion("q24", "Paper 1A · Question 24", "Which spectrum is used most directly to identify molecular fragments by mass-to-charge ratio?", ["Infrared", "Mass", "Visible", "Microwave"], 1),
    choiceQuestion("q25", "Paper 1A · Question 25", "Which signal is expected for a carboxylic acid in an infrared spectrum?", ["Broad O–H absorption", "No carbonyl absorption", "Only a sharp C–H signal", "An atomic emission line"], 1),
    choiceQuestion("q26", "Paper 1A · Question 26", "Which factor does a catalyst change?", ["Reaction enthalpy", "Equilibrium constant", "Activation energy", "Product identity"], 1),
    choiceQuestion("q27", "Paper 1A · Question 27", "What is the order with respect to X if doubling [X] quadruples rate?", ["Zero", "One", "Two", "Four"], 1),
    choiceQuestion("q28", "Paper 1A · Question 28", "Which observation best indicates precision?", ["A mean near the accepted value", "Repeated values close together", "A large uncertainty", "A zero systematic error by assumption"], 1),
    choiceQuestion("q29", "Paper 1A · Question 29", "Which glassware is best for delivering one fixed volume accurately?", ["Beaker", "Volumetric pipette", "Conical flask", "Evaporating basin"], 1),
    choiceQuestion("q30", "Paper 1A · Question 30", "Which graph linearizes a first-order decay in concentration?", ["[A] against time", "ln[A] against time", "1/[A] against time", "rate against 1/time"], 1),
    inkQuestion("q31", "Paper 1B · Data question 1", "Magnesium reacts with excess hydrochloric acid. Calculate the maximum volume of hydrogen at 100 kPa and 298 K produced from 0.486 g Mg. Use R = 8.31 J mol⁻¹ K⁻¹.", 5, ["chem-reference"], 2),
    shortQuestion("q32", "Paper 1B · Data question 2", "Explain, using collision theory, why powdered magnesium reacts faster than a ribbon of the same mass under identical conditions. Propose one controlled measurement of rate.", 5),
    inkQuestion("q33", "Paper 1B · Data question 3", "A 50.0 g water sample warms from 21.4°C to 29.8°C. Calculate the heat transferred and the molar enthalpy change if 0.0125 mol reacted. State one assumption and its likely effect.", 7, ["chem-reference"], 2),
    essayQuestion("q34", "Paper 1B · Data question 4", "Design an investigation to determine the rate law for a reaction between two aqueous reactants. Specify the data table, control variables, processing, uncertainty treatment and safety measures.", 8),
  ],
  paperTwoResources: [
    textResource("kinetics-data", "Original kinetics data", "For reaction X + Y → products at constant temperature:\nExperiment 1: [X] 0.10, [Y] 0.10, rate 2.0 × 10⁻⁴\nExperiment 2: [X] 0.20, [Y] 0.10, rate 8.0 × 10⁻⁴\nExperiment 3: [X] 0.20, [Y] 0.30, rate 2.4 × 10⁻³\nConcentrations are mol dm⁻³; rates are mol dm⁻³ s⁻¹."),
    textResource("chem-reference", "Reference data for this sample", "Relative atomic masses: H 1.01, C 12.01, O 16.00, Na 22.99, Mg 24.31, Cl 35.45\nSpecific heat capacity of water: 4.18 J g⁻¹ K⁻¹\nFaraday constant: 9.65 × 10⁴ C mol⁻¹"),
  ],
  paperTwoQuestions: [
    inkQuestion("q1", "Question 1 — rate expression", "Determine the order with respect to X and Y, write the rate expression, and calculate the rate constant with units.", 8, ["kinetics-data"], 2),
    shortQuestion("q2", "Question 2 — equilibrium", "For an exothermic reversible reaction at equilibrium, explain the separate effects of increasing temperature and adding a catalyst on the equilibrium yield and the time to reach equilibrium.", 6),
    inkQuestion("q3", "Question 3 — organic chemistry", "Propose a two-step synthetic route from ethene to ethanoic acid. Give reagents, conditions and displayed or structural formulas for the organic intermediates.", 7, [], 2, "blank"),
    essayQuestion("q4", "Question 4 — spectroscopy", "A compound has molecular formula C₃H₆O₂. Explain how infrared and proton NMR evidence could distinguish methyl ethanoate from propanoic acid.", 9),
    inkQuestion("q5", "Question 5 — stoichiometry and gases", "A volatile liquid has mass 0.742 g and occupies 286 cm³ as a gas at 99.0 kPa and 373 K. Determine its molar mass, propose a molecular formula from a supplied empirical ratio, and evaluate one source of systematic error.", 10, ["chem-reference"], 2),
    inkQuestion("q6", "Question 6 — energetics", "Construct a Hess cycle to determine an unknown enthalpy of formation from combustion data. Then calculate the energy released by 12.0 g of the substance and state why the experimental value may be less exothermic.", 10, ["chem-reference"], 2),
    shortQuestion("q7", "Question 7 — acids and bases", "Calculate the pH of a weak monoprotic acid and of the buffer formed after partial neutralization. Explain the response of the buffer to a small addition of strong acid.", 10),
    inkQuestion("q8", "Question 8 — electrochemistry", "Use standard electrode potentials to predict the feasibility and direction of a redox reaction, write the overall equation, calculate E°cell and determine ΔG° at 298 K.", 10, ["chem-reference"], 2),
    essayQuestion("q9", "Question 9 — structure and bonding", "Compare the bonding, structure and resulting physical properties of sodium chloride, graphite, silicon dioxide and iodine. Include conductivity in solid and liquid states where applicable.", 10),
    shortQuestion("q10", "Question 10 — organic mechanisms", "For a route from propene to propanone, give reagents and conditions, classify each step, outline one mechanism with curly-arrow descriptions, and identify diagnostic spectroscopic evidence.", 10),
  ],
});

const physics = scienceSamples({
  subject: "physics",
  label: "Physics",
  materialsInstructions: "An approved calculator is required. Use the original reference data supplied within this sample; no external data booklet is needed.",
  paperOneResources: [textResource("physics-reference", "Reference data for this sample", "g = 9.81 m s⁻²\nSpeed of light c = 3.00 × 10⁸ m s⁻¹\nElementary charge e = 1.60 × 10⁻¹⁹ C")],
  paperOneQuestions: [
    choiceQuestion("q1", "Paper 1A · Question 1", "A car travels 60 m east and then 20 m west. What is its displacement?", ["80 m east", "40 m east", "40 m west", "80 m west"], 1),
    choiceQuestion("q2", "Paper 1A · Question 2", "Two identical resistors are connected in parallel. Their combined resistance is", ["twice one resistor", "equal to one resistor", "half one resistor", "zero"], 1),
    choiceQuestion("q3", "Paper 1A · Question 3", "Which property remains constant when a wave crosses a boundary into a new medium?", ["Speed", "Wavelength", "Frequency", "Amplitude"], 1),
    choiceQuestion("q4", "Paper 1A · Question 4", "Which quantity is measured in joules per coulomb?", ["Current", "Potential difference", "Resistance", "Power"], 1),
    choiceQuestion("q5", "Paper 1A · Question 5", "What is the gradient of a velocity–time graph?", ["Displacement", "Acceleration", "Momentum", "Power"], 1),
    choiceQuestion("q6", "Paper 1A · Question 6", "Which quantity is conserved in every isolated collision?", ["Kinetic energy", "Momentum", "Speed of each object", "Force"], 1),
    choiceQuestion("q7", "Paper 1A · Question 7", "A force acts perpendicular to displacement. What work does it do?", ["Zero", "Maximum positive", "Maximum negative", "Equal to force"], 1),
    choiceQuestion("q8", "Paper 1A · Question 8", "Which expression is power?", ["Energy × time", "Energy ÷ time", "Force ÷ distance", "Momentum × time"], 1),
    choiceQuestion("q9", "Paper 1A · Question 9", "What provides centripetal acceleration in a circular orbit?", ["A tangential force only", "A resultant force toward the centre", "No force", "A force away from the centre"], 1),
    choiceQuestion("q10", "Paper 1A · Question 10", "Which change doubles gravitational field strength at fixed mass?", ["Double distance", "Halve distance", "Increase distance by √2", "Reduce distance by 1/√2"], 1),
    choiceQuestion("q11", "Paper 1A · Question 11", "Temperature is proportional to which microscopic quantity for an ideal gas?", ["Total potential energy", "Mean random kinetic energy", "Number of particles only", "Container volume only"], 1),
    choiceQuestion("q12", "Paper 1A · Question 12", "During melting at constant pressure, added energy mainly increases", ["mean kinetic energy", "intermolecular potential energy", "mass", "temperature immediately"], 1),
    choiceQuestion("q13", "Paper 1A · Question 13", "Which wave phenomenon demonstrates superposition?", ["Interference", "Radioactive decay", "Charge quantization", "Thermal expansion"], 1),
    choiceQuestion("q14", "Paper 1A · Question 14", "A standing wave node has", ["maximum displacement", "zero displacement at all times", "maximum speed at all times", "no neighbouring antinode"], 1),
    choiceQuestion("q15", "Paper 1A · Question 15", "Which change increases diffraction?", ["Aperture much wider than wavelength", "Aperture comparable to wavelength", "Higher amplitude only", "Shorter path only"], 1),
    choiceQuestion("q16", "Paper 1A · Question 16", "What is current?", ["Energy per charge", "Charge per time", "Force per charge", "Power per resistance"], 1),
    choiceQuestion("q17", "Paper 1A · Question 17", "For an ohmic conductor at constant temperature, resistance is", ["V/I", "VI", "I/V", "Vt"], 1),
    choiceQuestion("q18", "Paper 1A · Question 18", "Which field direction is defined by the force on a positive test charge?", ["Electric", "Gravitational", "Temperature", "Pressure"], 1),
    choiceQuestion("q19", "Paper 1A · Question 19", "A charged particle enters a uniform magnetic field parallel to the field. Its magnetic force is", ["maximum", "zero", "opposite to velocity", "along the field"], 1),
    choiceQuestion("q20", "Paper 1A · Question 20", "Electromagnetic induction requires a change in", ["resistance only", "magnetic flux linkage", "electric charge", "mass"], 1),
    choiceQuestion("q21", "Paper 1A · Question 21", "Which statement about photons is correct?", ["Energy is hf", "Energy is independent of frequency", "All photons have equal momentum", "Photons carry charge"], 1),
    choiceQuestion("q22", "Paper 1A · Question 22", "What determines the activity of a radioactive sample?", ["Decay constant and number of undecayed nuclei", "Temperature only", "Pressure only", "Sample shape only"], 1),
    choiceQuestion("q23", "Paper 1A · Question 23", "Which interaction binds protons and neutrons in a nucleus?", ["Gravitational", "Strong", "Electrostatic only", "Frictional"], 1),
    choiceQuestion("q24", "Paper 1A · Question 24", "Which graph should be linear for exponential radioactive decay?", ["N against t", "ln N against t", "1/N against t", "N² against t"], 1),
    choiceQuestion("q25", "Paper 1A · Question 25", "Which statement distinguishes random from systematic uncertainty?", ["Random uncertainty causes scatter", "Random uncertainty shifts every result equally", "Systematic uncertainty is removed by repeats alone", "Systematic uncertainty never affects accuracy"], 1),
    inkQuestion("q26", "Paper 1B · Data question 1", "A 0.40 kg ball is projected vertically upward at 12.0 m s⁻¹. Neglect air resistance. Calculate its maximum height above the launch point and the time taken to return.", 5, ["physics-reference"], 2),
    inkQuestion("q27", "Paper 1B · Data question 2", "A 6.0 Ω resistor and a 3.0 Ω resistor are connected in parallel to a 12 V supply. Draw the circuit and calculate the total current and power supplied.", 5, [], 1, "blank"),
    inkQuestion("q28", "Paper 1B · Data question 3", "A student records the period of a pendulum at five lengths. Describe how to process the data to determine g, including the graph, gradient relationship and treatment of uncertainty.", 5, ["physics-reference"], 2),
    essayQuestion("q29", "Paper 1B · Data question 4", "Design an investigation of how light intensity affects the current from a photovoltaic cell. Include a labelled arrangement, variables, repeated measurements, graph and two safety or validity controls.", 5),
  ],
  paperTwoResources: [
    textResource("induction-data", "Original induction investigation", "A coil of 250 turns and area 3.2 × 10⁻³ m² is perpendicular to a uniform magnetic field. The field falls linearly from 0.80 T to 0.20 T in 0.15 s. The coil resistance is 4.0 Ω."),
    textResource("physics-reference", "Reference data for this sample", "g = 9.81 m s⁻²\nG = 6.67 × 10⁻¹¹ N m² kg⁻²\nSpeed of light c = 3.00 × 10⁸ m s⁻¹\nElementary charge e = 1.60 × 10⁻¹⁹ C"),
  ],
  paperTwoQuestions: [
    inkQuestion("q1", "Question 1 — electromagnetic induction", "Calculate the magnitude of the average induced emf and current. State the direction principle used to determine the induced current.", 7, ["induction-data"], 2),
    inkQuestion("q2", "Question 2 — fields", "A satellite moves in a circular orbit of radius 7.2 × 10⁶ m around a planet of mass 6.0 × 10²⁴ kg. Calculate its orbital speed and period. Use G = 6.67 × 10⁻¹¹ N m² kg⁻².", 8, [], 2),
    shortQuestion("q3", "Question 3 — quantum physics", "Explain why the photoelectric effect supports a particulate model of electromagnetic radiation. Refer to threshold frequency and intensity.", 6),
    essayQuestion("q4", "Question 4 — thermal physics", "A student claims that temperature measures the total energy stored in an object. Evaluate the claim using microscopic models and two contrasting examples.", 9),
    inkQuestion("q5", "Question 5 — mechanics", "A trolley moves down an incline with a resistive force proportional to speed. Derive the terminal speed, sketch speed against time, and use supplied measurements to estimate the proportionality constant.", 10, ["physics-reference"], 2),
    inkQuestion("q6", "Question 6 — oscillations", "A mass–spring system has amplitude 0.080 m and period 1.60 s. Determine its angular frequency, maximum speed and maximum acceleration, then calculate the speed at displacement 0.050 m.", 10, ["physics-reference"], 2),
    inkQuestion("q7", "Question 7 — wave behaviour", "Two coherent sources produce an interference pattern. Use path difference to locate maxima, calculate fringe separation for a double slit, and explain the effect of increasing slit separation.", 10, ["physics-reference"], 2),
    inkQuestion("q8", "Question 8 — electric fields", "An electron is accelerated through a potential difference and enters a uniform electric field. Calculate its speed, subsequent acceleration and deflection, stating the assumptions used.", 10, ["physics-reference"], 2),
    inkQuestion("q9", "Question 9 — nuclear physics", "Use mass data to calculate the binding energy per nucleon of a nucleus. Compare it with two neighbouring nuclei and explain what the comparison suggests about possible energy-releasing reactions.", 10, ["physics-reference"], 2),
    essayQuestion("q10", "Question 10 — energy and climate", "Evaluate a simplified planetary energy-balance model. Explain albedo and emissivity, calculate an equilibrium temperature from supplied values, and discuss two limitations of the model.", 10, ["physics-reference"]),
  ],
});

export const STEM_SAMPLE_PAPERS = [
  ...mathematicsAA,
  ...mathematicsAI,
  ...biology,
  ...chemistry,
  ...physics,
];
