import { textResource } from "../helpers.ts";

export interface BiologyChoice {
  topic: string;
  prompt: string;
  options: [string, string, string, string];
  correctOption: number;
  answer: string;
  resource?: string;
}

export const BIOLOGY_MCQ_RESOURCES = [
  textResource("bio-transport", "Questions 7–10 · membrane transport study", `Original experiment. Researchers placed equal-sized plant tissue cylinders in sucrose solutions for 60 minutes at 25°C. Six independently sampled cylinders were used at each concentration. Cylinders were blotted by the same procedure before weighing. Sucrose did not cross the plasma membranes during the trial.
Sucrose / mol L⁻¹ | Mean mass change / % | Standard error / percentage points
0.00 | +12.0 | 0.8
0.20 | +5.0 | 0.6
0.40 | −3.0 | 0.5
0.60 | −10.0 | 0.9
Assume a straight-line relationship between the two measurements nearest zero mass change when estimating the isotonic concentration.`),
  textResource("bio-mitochondria", "Questions 14–17 · isolated mitochondria", `Original experiment. Equal amounts of isolated mitochondria were supplied with excess oxygen, respiratory substrate, ADP and phosphate. The table gives steady rates after treatment, relative to untreated mitochondria. U is a compound that allows protons to move across the inner membrane without passing through ATP synthase. B blocks electron transfer to oxygen. The preparations remained intact.
Treatment | Oxygen consumption | ATP production
None | 100 | 100
U | 155 | 12
B | 4 | 3
Rates are relative units. No claim about statistical significance is possible from these means alone.`),
  textResource("bio-signal", "Questions 22–25 · signaling pathway model", `Original model. An extracellular ligand binds receptor R. Activated R activates kinase K. K phosphorylates transcription factor T; phosphorylated T stimulates gene G. An enzyme P removes the phosphate from T. Arrows in the first line show activation. The second line shows the separate dephosphorylation reaction catalyzed by P.
Ligand → R → K → T-P → transcription of G
P catalyzes: T-P → T + phosphate
Without ligand, R is inactive. All proposed mutations affect only the activity named; assume no other pathway regulates G.`),
  textResource("bio-cross", "Questions 30–33 · two-gene test cross", `Original genetics study. A plant heterozygous at two linked loci has alleles arranged AB/ab. It is test-crossed with ab/ab. All four offspring phenotypes are equally viable and distinguishable. Offspring counts:
AB phenotype: 410
ab phenotype: 390
Ab phenotype: 102
aB phenotype: 98
Total: 1000
The phenotype records the gamete from the heterozygous parent. Assume the sample estimates the recombination frequency adequately.`),
  textResource("bio-reporter", "Questions 36–39 · gene regulation experiment", `Original experiment. Researchers introduced a reporter gene into cultured animal cells. The reporter's coding sequence and promoter were identical in all constructs. Constructs differed only in a distant regulatory DNA region. All cells received equal DNA amounts and a second constitutively expressed control reporter. Values below are reporter expression divided by control-reporter expression, averaged over six independent cultures.
Construct | No hormone | Hormone added
Intact regulatory region | 2 | 20
Regulatory region deleted | 2 | 3
Intact region, receptor gene disrupted in cells | 2 | 2
The hormone enters the cells and binds an intracellular receptor.`),
  textResource("bio-phylogeny", "Questions 44–47 · evolutionary evidence", `Original simplified rooted tree. O is an outgroup. All terminal labels represent living populations. The topology, not the spacing, is the information supplied.
root
├─ O
└─ node 1
   ├─ A
   └─ node 2
      ├─ B
      └─ node 3
         ├─ C
         └─ D
Independent DNA data: a derived 12-base insertion is absent in O and A but present at the same homologous site in B, C and D. Assume the insertion arose once and was not lost.`),
  textResource("bio-ecology", "Questions 54–57 · pond manipulation", `Original study. Twenty comparable outdoor pond tanks were randomly assigned to fish-present or fish-absent treatments (10 each). Initial algal and zooplankton populations were similar. Fish eat large zooplankton; large zooplankton graze algae. After four weeks:
Treatment | Mean large zooplankton / L | Mean chlorophyll a / µg L⁻¹
Fish absent | 48 | 6
Fish present | 12 | 24
Light and nutrient supply were held constant. Chlorophyll a is used as a measure of algal abundance. No toxin effect was studied.`),
];

export const BIOLOGY_CHOICES: BiologyChoice[] = [
  { topic: "Unit 1 · water", prompt: "A pond freezes at its surface while liquid water remains below. Which molecular property most directly explains why the ice floats?", options: ["Covalent bonds between water molecules become shorter on freezing.","Water molecules lose oxygen atoms as ice forms.","The nonpolar parts of water molecules repel one another.","Hydrogen bonds hold molecules in an open arrangement in ice."], correctOption: 3, answer: "D. Hydrogen bonding produces a relatively open lattice, lowering density; the intramolecular covalent bonds remain intact." },
  { topic: "Unit 1 · protein structure", prompt: "In a soluble enzyme, a mutation replaces an uncharged amino acid buried in its hydrophobic core with a charged amino acid. Which outcome is most directly plausible?", options: ["Altered interactions change folding and possibly the active site.","Every peptide bond in the protein is hydrolyzed.","The genetic code gains a new codon.","The amino-acid sequence becomes a carbohydrate."], correctOption: 0, answer: "A. A charged side chain in a hydrophobic environment can disrupt tertiary interactions and hence enzyme shape, without requiring complete hydrolysis." },
  { topic: "Unit 1 · macromolecules", prompt: "A student hydrolyzes a purified polymer and detects only glucose monomers. Which additional observation would best distinguish cellulose from starch?", options: ["Whether the material contains hydrogen","Whether carbon is present","Whether hydrolysis consumed water","The type of glycosidic linkage joining adjacent glucose units"], correctOption: 3, answer: "D. Cellulose has beta linkages while starch has alpha linkages; both contain C/H/O and are hydrolyzed using water." },
  { topic: "Unit 1 · lipids", prompt: "A membrane lipid contains a phosphate-bearing polar head and two nonpolar fatty-acid tails. In water, which arrangement best reduces exposure of the tails to water?", options: ["All heads and tails mixed uniformly throughout the water","Heads in the bilayer interior and tails on both outer surfaces","A bilayer with heads facing water and tails facing inward","A covalent chain connecting every head to every tail"], correctOption: 2, answer: "C. Amphipathic phospholipids form a bilayer with hydrophilic heads exposed and hydrophobic tails shielded." },
  { topic: "Unit 1 · nucleic acids", prompt: "A double-stranded DNA sample contains 24% adenine. What percentage of its nucleotides contain cytosine?", options: ["48%","52%","26%","24%"], correctOption: 2, answer: "C. A=T=24%, leaving 52% for G+C; G=C=26%." },
  { topic: "Unit 1 · dehydration synthesis", prompt: "A cell links 50 amino acids into one unbranched polypeptide. Ignoring later processing, how many peptide bonds are formed?", options: ["48","49","25","50"], correctOption: 1, answer: "B. A linear chain of n residues has n−1 links, so 49 peptide bonds." },
  { topic: "Unit 2 · osmosis", resource: "bio-transport", prompt: "Using the specified interpolation, the sucrose concentration producing no net mass change is closest to", options: ["0.325 mol L⁻¹","0.500 mol L⁻¹","0.250 mol L⁻¹","0.125 mol L⁻¹"], correctOption: 0, answer: "A. Zero lies 5/8 of the way from +5 to −3: 0.20+(5/8)(0.20)=0.325 mol L⁻¹." },
  { topic: "Unit 2 · water potential", resource: "bio-transport", prompt: "Why did the cylinders in 0.60 mol L⁻¹ sucrose lose mass?", options: ["Water moved out toward the lower external water potential.","The solution had a higher water potential than the cells.","Sucrose converted intracellular water into ATP.","Active transport pumped all water out of the cells."], correctOption: 0, answer: "A. The more negative external water potential favors net outward water movement by osmosis." },
  { topic: "Unit 2 · experimental controls", resource: "bio-transport", prompt: "Why is standardized blotting important?", options: ["It limits variation in surface liquid included in measured mass.","It prevents sucrose from dissolving.","It ensures that osmosis proceeds only inward.","It makes every cylinder genetically identical."], correctOption: 0, answer: "A. Different retained surface liquid could masquerade as tissue mass change; standardized blotting reduces that measurement confound." },
  { topic: "Unit 2 · membrane transport", resource: "bio-transport", prompt: "A treatment blocks aquaporins without changing solute concentration or killing cells. What is the best prediction for the first few minutes?", options: ["Water will move against its potential gradient.","Water movement will be slower, but its favored direction is unchanged.","Sucrose will immediately become permeable to the membrane.","The bilayer will necessarily disappear."], correctOption: 1, answer: "B. Aquaporins increase water permeability; blocking them slows flux without reversing the thermodynamic gradient." },
  { topic: "Unit 2 · cell size", prompt: "Two spherical cells have radii r and 2r. Compared with the smaller cell, the larger cell's surface-area-to-volume ratio is", options: ["four times as large","half as large","unchanged","twice as large"], correctOption: 1, answer: "B. For a sphere, SA/V=3/r, so doubling r halves the ratio." },
  { topic: "Unit 2 · compartmentalization", prompt: "A cell produces a protein that will be secreted. Which path correctly places major processing and transport steps in order?", options: ["Plasma membrane → ribosome → chloroplast → Golgi apparatus","Mitochondrion → smooth endoplasmic reticulum → nucleus","Golgi apparatus → nucleus → lysosome → cytosol","Rough endoplasmic reticulum → Golgi apparatus → secretory vesicle → plasma membrane"], correctOption: 3, answer: "D. Secreted proteins enter the rough ER, are processed/sorted through the Golgi and delivered by vesicles to the plasma membrane." },
  { topic: "Unit 2 · endosymbiosis", prompt: "Which combination most strongly supports an endosymbiotic origin of mitochondria?", options: ["They contain nuclear chromosomes and are made anew by the Golgi.","They occur only in large organisms and contain cellulose.","They contain circular DNA, divide, and have ribosomes resembling bacterial ribosomes.","They have no membranes and cannot divide."], correctOption: 2, answer: "C. These inherited bacterial-like features jointly support descent from an engulfed prokaryote." },
  { topic: "Unit 3 · chemiosmosis", resource: "bio-mitochondria", prompt: "The data for U most directly support which conclusion?", options: ["Oxygen consumption alone guarantees a high ATP yield.","ATP synthesis uses no membrane proteins.","A proton gradient is needed to couple electron transport to efficient ATP synthesis.","Electron transfer ceases whenever protons cross the inner membrane."], correctOption: 2, answer: "C. U permits substantial electron transport/oxygen consumption while dissipating the gradient and greatly reducing ATP synthesis." },
  { topic: "Unit 3 · respiration", resource: "bio-mitochondria", prompt: "In untreated mitochondria, oxygen directly participates as", options: ["the carbon source for acetyl-CoA","the phosphate donor to ADP","the terminal electron acceptor, forming water","the enzyme that splits glucose"], correctOption: 2, answer: "C. At the end of the respiratory chain oxygen accepts electrons and protons to form water." },
  { topic: "Unit 3 · energetic calculation", resource: "bio-mitochondria", prompt: "What is the percentage decrease in ATP-production rate under U relative to the untreated preparation?", options: ["12%","143%","155%","88%"], correctOption: 3, answer: "D. (100−12)/100×100=88%." },
  { topic: "Unit 3 · redox", resource: "bio-mitochondria", prompt: "Immediately after B is added, before respiratory substrate is exhausted, which change is expected?", options: ["ATP synthase begins creating oxygen from carbon dioxide.","Upstream electron carriers become more reduced.","All NADH is instantly oxidized to NAD⁺.","The oxygen-consumption rate rises above that under U."], correctOption: 1, answer: "B. Blocking downstream electron transfer prevents efficient carrier oxidation, allowing reduced carriers such as NADH to accumulate." },
  { topic: "Unit 3 · enzyme kinetics", prompt: "At fixed enzyme concentration, doubling a very high substrate concentration causes almost no further increase in reaction rate. Which explanation best fits?", options: ["Activation energy has become negative.","The substrate has become an enzyme.","Most active sites are already occupied; enzyme turnover limits the rate.","The enzyme changed the equilibrium constant."], correctOption: 2, answer: "C. Near saturation, enzyme active sites are occupied for most of the time and rate approaches a maximum set by enzyme amount and turnover." },
  { topic: "Unit 3 · photosynthesis", prompt: "A leaf is supplied with water containing the isotope oxygen-18 while its carbon dioxide contains ordinary oxygen. During photosynthesis, oxygen-18 will most directly appear in", options: ["new nitrogen bases","the magnesium in chlorophyll","the carbon atoms of glucose","the oxygen gas released by the light reactions"], correctOption: 3, answer: "D. Photosystem II splits water; oxygen atoms in released O₂ come from water, not CO₂." },
  { topic: "Unit 3 · carbon fixation", prompt: "If light reactions stop but the Calvin cycle briefly continues, which stored molecules will be consumed directly to reduce carbon intermediates and regenerate the CO₂ acceptor?", options: ["Oxygen and DNA","Carbon dioxide and ADP as energy donors","ATP and NADPH","NADH and glycogen only"], correctOption: 2, answer: "C. The Calvin cycle uses ATP for energy and NADPH for reducing electrons; these are normally replenished by light reactions." },
  { topic: "Unit 3 · fermentation", prompt: "Yeast cells produce ethanol when oxygen is absent. How does fermentation allow glycolysis to continue?", options: ["It replaces all enzymes in glycolysis.","It converts every glucose directly into 36 ATP.","It creates an inner-membrane proton gradient using oxygen.","It regenerates NAD⁺ by oxidizing NADH."], correctOption: 3, answer: "D. Reduction of an organic acceptor reoxidizes NADH, providing NAD⁺ required by glycolysis." },
  { topic: "Unit 4 · signaling model", resource: "bio-signal", prompt: "A mutation makes K active even when R is inactive. Which result is predicted without ligand?", options: ["Transcription of G can occur downstream of constitutively active K.","T can no longer contain amino acids.","P must become a receptor.","G cannot be transcribed because ligand is the RNA template."], correctOption: 0, answer: "A. Constitutively active K bypasses the need for R activation and can phosphorylate T." },
  { topic: "Unit 4 · signal termination", resource: "bio-signal", prompt: "If P is inhibited after ligand is removed, which change is most likely?", options: ["T-P disappears more rapidly.","T remains phosphorylated for longer.","The promoter of G is deleted.","Ligand is converted into DNA."], correctOption: 1, answer: "B. Reduced phosphate removal delays T inactivation and can prolong downstream expression." },
  { topic: "Unit 4 · experimental design", resource: "bio-signal", prompt: "Which measurement most directly tests whether a drug inhibits the step between K and T?", options: ["Total water mass in the culture dish","Ligand color after heating it alone","The number of chromosomes in an unrelated organism","T phosphorylation with purified active K, with and without the drug"], correctOption: 3, answer: "D. Holding K active and measuring its downstream substrate's phosphorylation isolates the proposed affected step." },
  { topic: "Unit 4 · receptor structure", resource: "bio-signal", prompt: "R still binds ligand, but a deletion removes its domain that activates K. What is expected?", options: ["Ligand binding no longer efficiently activates this pathway.","G is always maximally expressed.","P becomes unable to remove phosphate.","The ligand automatically phosphorylates T."], correctOption: 0, answer: "A. Reception without a functional transducing domain cannot efficiently pass the signal to K." },
  { topic: "Unit 4 · negative feedback", prompt: "Blood glucose rises after a meal, stimulating insulin secretion. Insulin increases glucose uptake, and insulin secretion falls as glucose returns toward its usual range. This is negative feedback because", options: ["the response amplifies the original rise without limit","all communication occurs by direct DNA transfer","the response permanently eliminates glucose","the response reduces the stimulus that initiated it"], correctOption: 3, answer: "D. Glucose removal counteracts the initial increase, reducing the stimulus for insulin release." },
  { topic: "Unit 4 · cell cycle", prompt: "A drug prevents spindle microtubules from attaching correctly to kinetochores. Which checkpoint most directly prevents chromosome separation in affected cells?", options: ["The checkpoint controlling fertilization","The checkpoint determining whether nutrients enter a lysosome","The spindle-assembly checkpoint before anaphase","The checkpoint that removes introns"], correctOption: 2, answer: "C. The spindle checkpoint delays anaphase until chromosomes have appropriate spindle attachments." },
  { topic: "Unit 4 · cancer", prompt: "A tumor-suppressor protein normally halts division when DNA damage is detected. A cell loses both functional copies of its gene. Which consequence is most plausible?", options: ["The mutation guarantees beneficial changes in offspring.","Every mutation is immediately repaired.","The cell may divide despite unrepaired DNA damage.","The cell necessarily loses all ribosomes."], correctOption: 2, answer: "C. Loss of a damage-responsive brake permits inappropriate cell-cycle progression; it does not guarantee a particular tumor outcome." },
  { topic: "Unit 4 · cell-cycle data", prompt: "In a dividing cell culture, most cells have either 2C or 4C DNA, and a smaller group have values between 2C and 4C. The intermediate group most likely consists of cells", options: ["in G₁ before DNA replication","in S phase synthesizing DNA","that have finished mitosis and cytokinesis","undergoing meiosis II after chromosome separation"], correctOption: 1, answer: "B. DNA content increases continuously from 2C to 4C during S phase." },
  { topic: "Unit 5 · linkage", resource: "bio-cross", prompt: "The estimated recombination frequency between the loci is", options: ["40%","10%","20%","80%"], correctOption: 2, answer: "C. Recombinants Ab+aB=102+98=200 of 1000, hence 20%." },
  { topic: "Unit 5 · meiosis", resource: "bio-cross", prompt: "Which event can directly generate the Ab and aB gametes from this heterozygote?", options: ["DNA replication after fertilization","Exchange between nonsister chromatids of homologous chromosomes in prophase I","Conversion of every recessive allele into a dominant allele","Separation of sister chromatids without any earlier crossing over"], correctOption: 1, answer: "B. Crossing over between the linked loci in prophase I produces recombinant chromatids." },
  { topic: "Unit 5 · test crosses", resource: "bio-cross", prompt: "Why is the ab/ab parent useful in this cross?", options: ["It prevents meiosis in the heterozygote.","It guarantees all offspring are homozygous dominant.","Its gametes contribute only a and b, allowing offspring phenotype to reveal the other parent's gamete.","It forces the two genes to become unlinked."], correctOption: 2, answer: "C. The recessive tester does not mask the alleles contributed by the heterozygote." },
  { topic: "Unit 5 · genetic prediction", resource: "bio-cross", prompt: "If a second pair of loci independently assort, which offspring ratio is expected in an equivalent two-gene test cross with complete dominance?", options: ["1: 0: 0: 1","3: 1: 0: 0","9: 3: 3: 1","1: 1: 1: 1"], correctOption: 3, answer: "D. Independent assortment gives four equally likely gametes from AaBb, each revealed by aabb." },
  { topic: "Unit 5 · inheritance", prompt: "Two unaffected parents have an affected daughter for a rare fully penetrant recessive trait. Assume no new mutation. Which inheritance pattern is consistent with this observation?", options: ["X-linked recessive with an unaffected father","Mitochondrial inheritance with an unaffected homoplasmic mother","Autosomal recessive with both parents heterozygous","Y-linked inheritance"], correctOption: 2, answer: "C. Two Aa parents can have an aa daughter. Under stated complete penetrance, an X-linked-recessive daughter would require an affected father." },
  { topic: "Unit 5 · probability", prompt: "For the cross Aa × Aa with complete dominance and independent offspring outcomes, what is the probability that the first two offspring both have the recessive phenotype?", options: ["1/4","1/16","3/16","1/2"], correctOption: 1, answer: "B. Each offspring has P(aa)=1/4; independent joint probability=(1/4)²=1/16." },
  { topic: "Unit 6 · regulatory DNA", resource: "bio-reporter", prompt: "Which interpretation best fits the regulatory-region deletion?", options: ["The region contributes to hormone-dependent enhancement of transcription.","The hormone always destroys reporter mRNA.","Deleting the region eliminates every promoter in the cell.","The region is the only template for the reporter's amino acids."], correctOption: 0, answer: "A. Basal expression is maintained but hormone response is greatly reduced when the region is removed, consistent with an enhancer-like function." },
  { topic: "Unit 6 · expression calculation", resource: "bio-reporter", prompt: "For the intact construct, hormone produces what fold-change relative to no hormone?", options: ["10-fold","2-fold","20-fold","18-fold"], correctOption: 0, answer: "A. Fold-change is 20/2=10, not the difference 18." },
  { topic: "Unit 6 · experimental normalization", resource: "bio-reporter", prompt: "Why divide reporter expression by the control-reporter expression?", options: ["To ensure the experimental reporter is never transcribed","To make all regulatory sequences identical","To help control for variation in DNA delivery and cell amount","To convert the hormone into an enzyme"], correctOption: 2, answer: "C. A constitutive reference helps normalize transfection efficiency and sample amount, although it must itself remain unaffected by treatment." },
  { topic: "Unit 6 · causal inference", resource: "bio-reporter", prompt: "Which extra experiment would best test whether the receptor directly binds the regulatory DNA?", options: ["Measure the mass of hormone before adding cells.","Measure binding between purified receptor and isolated regulatory DNA, with nonspecific DNA and no-receptor controls.","Delete all ribosomes and measure cell survival.","Count cells without examining DNA."], correctOption: 1, answer: "B. Testing purified receptor with isolated DNA excludes other cellular proteins that could bridge an indirect association. Nonspecific DNA and no-receptor controls assess specificity and background; expression results alone do not establish direct binding." },
  { topic: "Unit 6 · replication", prompt: "Why is one new DNA strand synthesized in short fragments at a replication fork?", options: ["The two parental strands have the same direction.","DNA polymerase adds nucleotides only to a 3′ end, while the templates are antiparallel.","DNA polymerase can synthesize only RNA.","Hydrogen bonds can form only every 100 nucleotides."], correctOption: 1, answer: "B. Polymerase synthesis is 5′→3′ on both antiparallel templates, so synthesis away from the moving fork proceeds in fragments." },
  { topic: "Unit 6 · mutation", prompt: "Within a protein-coding sequence, one nucleotide is deleted near the start and no compensating insertion occurs. Which result is most likely?", options: ["Transcription becomes impossible in every cell.","Only the last amino acid is necessarily affected.","Every codon after the deletion is necessarily synonymous.","The reading frame shifts downstream, often producing an early stop codon."], correctOption: 3, answer: "D. A single-base deletion not divisible by three shifts codon grouping and commonly changes many residues and termination." },
  { topic: "Unit 6 · RNA processing", prompt: "Two cell types have the same gene but produce proteins differing by an internal amino-acid segment. Their mature mRNAs differ by one exon. Which mechanism best explains this?", options: ["Independent assortment of chromosomes in every transcription event","Replacement of ribosomes by DNA polymerase","Alternative splicing of the same primary RNA transcript","Hydrolysis of all peptide bonds after translation"], correctOption: 2, answer: "C. Different exon inclusion during splicing creates different mature mRNAs and protein isoforms from one gene." },
  { topic: "Unit 6 · biotechnology", prompt: "A PCR tube contains template DNA, thermostable polymerase, nucleotides and buffer but lacks primers. Why will efficient amplification fail?", options: ["Primers supply all of the template's carbon atoms.","Polymerase needs a paired primer with a free 3′ end to extend.","DNA must be translated before it can be copied.","Thermostable polymerase functions only at 0°C."], correctOption: 1, answer: "B. DNA polymerase cannot initiate a new strand de novo; primers provide an annealed 3′-OH." },
  { topic: "Unit 7 · phylogeny", resource: "bio-phylogeny", prompt: "Which pair shares the most recent common ancestor in the tree?", options: ["B and D","O and A","A and B","C and D"], correctOption: 3, answer: "D. C and D meet at node 3, which is descended from the ancestors shared with B or A." },
  { topic: "Unit 7 · shared derived characters", resource: "bio-phylogeny", prompt: "On the stated single-origin assumption, the insertion most likely arose on the branch leading to", options: ["O only","node 2, the ancestor of B, C and D","the common ancestor of all five groups","A only"], correctOption: 1, answer: "B. Its distribution is explained by origin before B/C/D diverged but after their lineage split from A." },
  { topic: "Unit 7 · tree interpretation", resource: "bio-phylogeny", prompt: "Which statement is justified by the topology alone?", options: ["Every branch represents exactly 1 million years.","A has evolved less than D.","B is equally related to C and D through their shared ancestor at node 2.","Living C is the direct ancestor of living D."], correctOption: 2, answer: "C. B's most recent common ancestor with C is the same as with D. Tip spacing does not specify elapsed time or evolutionary progress." },
  { topic: "Unit 7 · phylogenetic evidence", resource: "bio-phylogeny", prompt: "Why is a matching insertion at a homologous site stronger evidence of shared ancestry than similar body shape alone?", options: ["All DNA sequences mutate at the same rate.","Similar shape may arise independently under similar selection pressures.","DNA insertions are unaffected by evolution.","Body shape can never be inherited."], correctOption: 1, answer: "B. Convergent evolution can produce similar morphology; a homologous derived insertion is less easily explained by independent adaptation under the given assumptions." },
  { topic: "Unit 7 · Hardy–Weinberg", prompt: "In a large population at Hardy–Weinberg equilibrium, 9% of individuals are aa. What fraction is expected to be Aa?", options: ["0.42","0.49","0.09","0.21"], correctOption: 0, answer: "A. q²=0.09 gives q=0.30, p=0.70; 2pq=0.42." },
  { topic: "Unit 7 · genetic drift", prompt: "A storm leaves only 12 randomly surviving individuals from a large beetle population. A rare neutral allele becomes common among their descendants. Which process best explains the initial change?", options: ["Artificial selection by humans","Directed mutation because the beetles needed the allele","Independent assortment eliminating every allele","Genetic drift following a population bottleneck"], correctOption: 3, answer: "D. Random sampling of a small survivor population can change neutral allele frequencies without a selective advantage." },
  { topic: "Unit 7 · natural selection", prompt: "Before an antibiotic is used, a few bacteria already carry a resistance allele. During treatment they leave more descendants than susceptible bacteria. Which explanation is best?", options: ["Resistance proves that mutation is always beneficial.","The antibiotic instructed all cells to make the same useful mutation.","Selection increased the frequency of pre-existing heritable variation.","Individual susceptible cells evolved by deciding to survive."], correctOption: 2, answer: "C. Differential reproductive success changes allele frequencies; resistance need not originate in response to treatment." },
  { topic: "Unit 7 · reproductive isolation", prompt: "Two frog populations live in the same wetland but breed in different months. Even when they meet, few pairs form. The different breeding season is primarily", options: ["a mechanism requiring different chromosome numbers","a postzygotic barrier caused by hybrid sterility","a prezygotic temporal barrier reducing gene flow","evidence that the populations have identical gene pools"], correctOption: 2, answer: "C. Temporal separation acts before fertilization and reduces opportunities for mating." },
  { topic: "Unit 7 · selection and fitness", prompt: "At a locus, AA individuals leave an average of 4 surviving offspring, Aa leave 5, and aa leave 2 under the same conditions. If these differences persist, which outcome is most plausible?", options: ["Both alleles can be maintained by heterozygote advantage.","The A allele is necessarily neutral.","The a allele must disappear immediately.","The population must stop reproducing."], correctOption: 0, answer: "A. Higher heterozygote fitness can maintain both alleles through balancing selection." },
  { topic: "Unit 7 · origin of life evidence", prompt: "A laboratory RNA molecule both stores a sequence and catalyzes a reaction. Why is this relevant to hypotheses about early life?", options: ["It proves the exact location where life began.","It shows that one molecular class can have informational and catalytic roles.","It demonstrates that RNA contains no genetic information.","It shows that all modern proteins are unnecessary."], correctOption: 1, answer: "B. Dual function supports the plausibility of RNA-based early systems without establishing a complete historical account." },
  { topic: "Unit 8 · trophic interactions", resource: "bio-ecology", prompt: "Which mechanism best accounts for the higher chlorophyll concentration when fish are present?", options: ["Fish necessarily add a toxin that kills algae.","Fish produce all of the algae by mitosis.","Algae eat the fish and acquire their chlorophyll.","Fish reduce grazers, indirectly releasing algae from grazing pressure."], correctOption: 3, answer: "D. Fish predation reduces zooplankton grazing, a trophic cascade that permits greater algal abundance." },
  { topic: "Unit 8 · experimental unit", resource: "bio-ecology", prompt: "What is the independent experimental unit?", options: ["Each molecule of chlorophyll","Each pond tank","Each fish gill","Each reading from one water sample"], correctOption: 1, answer: "B. Treatment was independently assigned at tank level; repeated readings within a tank are not independent treatment replicates." },
  { topic: "Unit 8 · quantitative ecology", resource: "bio-ecology", prompt: "Relative to fish-absent tanks, the mean zooplankton abundance in fish-present tanks decreased by", options: ["25%","300%","75%","36%"], correctOption: 2, answer: "C. (48−12)/48×100=75%." },
  { topic: "Unit 8 · limits of inference", resource: "bio-ecology", prompt: "Which conclusion goes beyond the evidence?", options: ["Fish treatment is associated with lower mean zooplankton abundance.","The manipulated food web can show indirect effects.","Adding fish will improve biodiversity in every natural pond.","The experiment tests a specific fish–grazer–algae interaction."], correctOption: 2, answer: "C. The short tank study does not measure all biodiversity or justify universal effects across different natural systems." },
  { topic: "Unit 8 · population growth", prompt: "A population follows dN/dt=rN(1−N/K), with r=0.20 year⁻¹, K=1000 and N=500. What is its predicted instantaneous growth rate?", options: ["100 individuals year⁻¹","200 individuals year⁻¹","20 individuals year⁻¹","50 individuals year⁻¹"], correctOption: 3, answer: "D. 0.20×500×(1−500/1000)=50 individuals year⁻¹." },
  { topic: "Unit 8 · energy flow", prompt: "A grassland has gross primary productivity of 1800 kJ m⁻² year⁻¹ and producer respiration of 700 kJ m⁻² year⁻¹. Its net primary productivity is", options: ["1100 kJ m⁻² year⁻¹","2500 kJ m⁻² year⁻¹","700 kJ m⁻² year⁻¹","1800 kJ m⁻² year⁻¹"], correctOption: 0, answer: "A. NPP=GPP−producer respiration=1800−700=1100 kJ m⁻² year⁻¹." },
  { topic: "Unit 8 · biodiversity", prompt: "Two communities each contain four species and 100 individuals. Community X has 25 of each species; community Y has 97 of one species and 1 of each other species. Which comparison is correct?", options: ["Y has greater richness because one species is abundant.","Evenness must be equal because total abundance is equal.","X has fewer species than Y.","Richness is equal, but X has greater evenness."], correctOption: 3, answer: "D. Both have richness 4, but the uniform distribution in X has higher evenness." },
];
