/** Original simulated nonfiction. All people, institutions and project data are fictional. */
export const AP_ENGLISH_READING_A = `Reading set A — The index is not the archive
This original simulated public essay is attributed to the fictional municipal archivist Imani Vale, addressing residents considering a town archive's digitisation budget. All events and institutions are invented for this practice examination.

[1] A woman came to our reading room carrying a photograph of a street that officially had never flooded. In the photograph, her grandfather stood on a chair outside a shop, holding a broom above a brown, level world. She wanted to know the year. Our new search portal offered hundreds of results for “flood,” but none named her street. My first impulse was to refine the search. Her first impulse was to turn the photograph over. On the back, a child had written, “The day the milk came by boat.” We had been asking the archive a question in the archive's vocabulary. The photograph suggested another language.

[2] We eventually found the event under “temporary interruption of deliveries,” in a ledger belonging to the transport office. The water had entered the records through its inconvenience to commerce, not through its height against a doorstep. No clerk had necessarily intended to hide a flood. A clerk had needed to record a delivery problem. Yet the distinction mattered to a resident whose account of her family's life seemed to contradict the town's searchable memory. An index is not merely a smaller archive. It is an argument about the routes by which people should be able to enter one.

[3] I am sometimes invited to tell this story as a warning against computers. That invitation mistakes the instrument for the decision. Before we scanned the ledger, only a person able to travel here during a narrow weekday opening could have read it. The portal has allowed former residents, shift workers and students in other places to examine records that previously required a train ticket and a patient morning. To abandon it in the name of authenticity would restore a very authentic exclusion. The question is not whether a screen can replace a dusty box. It is what assistance must accompany either of them.

[4] A search result looks finished. It arrives in a neat rectangle, with a title and a date, as if those were properties as natural as the paper's weight. Behind the rectangle are uncertain identifications, inherited filing categories and choices about which handwritten words to transcribe. Making these decisions visible would not make the records useless. It would make them answerable. A note saying “street name uncertain” may help a resident more than a confident label borrowed from an unreliable map. Precision sometimes requires us to display the limits of our precision instead of polishing them away.

[5] There is a danger on the other side, too. A missing result is not proof of a suppressed history. The relevant file may have been lost, the spelling may have changed, or the event may never have generated an official document. Suspicion can begin a worthwhile inquiry; it cannot do the inquiry's work. We should therefore teach users how to follow an entry back to its source, how to compare records produced for different purposes, and how to distinguish an absence in the catalogue from an absence in the past. That teaching is not an apology for the collection. It is part of providing access to it.

[6] Next month's budget offers a choice between scanning another large batch of pages and employing a part-time assistant to improve descriptions of pages already available. The first option produces an impressive number for an annual report. The second may enable someone to find the one page that changes a question. We need both activities eventually, but they should not be confused. Residents could suggest names and connections, while staff preserve the original descriptions and identify the evidence behind revisions. Public participation would then add a documented layer, not quietly replace an inconvenient record with a popular recollection.

[7] The woman left with a date, a copy of the ledger entry and a new question about the boat. That last item was not a failure of our service. A useful archive does not conclude every conversation it begins. It equips people to continue a conversation with evidence, including evidence that may correct us. Let us build a portal that opens onto a workshop rather than one that pretends to be a verdict. The town's memory will be stronger when its citizens can see not only what we have found, but how a finding can be questioned.`;

export const AP_ENGLISH_READING_B = `Reading set B — What the notebook keeps
This original simulated science essay is attributed to the fictional field researcher Rowan Merek and intended for a general-interest magazine. The fieldwork described is invented; no actual study is reported.

[1] On the map I brought to the hillside, the boundary between two kinds of rock was a clean red line. On the hillside, it was bracken, loose stones and an afternoon of uncertainty. My receiver could tell me where I stood to a precision that would have astonished the researchers whose notebooks I had borrowed. It could not tell me whether the grey material under my boot belonged to the ridge or had slipped down from somewhere above it. Location was no longer my principal difficulty. Deciding what, exactly, I had located was.

[2] The old notebooks initially seemed an embarrassment beside the instrument. Their pages contained crossed-out numbers, unfinished sketches and a recurring complaint about a gate that would not open. One researcher had drawn a specimen three times, then written, “Probably transported; compare upper slope.” I had expected the notebooks to supply answers to the gaps in the published map. Instead, they preserved the questions that the map's orderly colours had absorbed. The tentative word “probably” was not a blemish left by an inattentive editor. It was information about the strength of the observation.

[3] A map must simplify. A traveller does not need every argument about a contour, any more than a reader needs the printer's invoice beside each paragraph of an essay. But useful simplification is not the same as the disappearance of its working history. When a boundary is challenged, an investigator needs to know whether it rested on five exposed outcrops or on one hurried glimpse through vegetation. The map tells us what its maker judged. The notebook can tell us what the maker had an opportunity to judge, a difference that becomes decisive when the landscape or the question changes.

[4] At noon I reached the stream named in an earlier survey. My receiver confirmed the coordinates; the stream refused the description. It ran several metres away, behind a recently repaired bank. In the notebook, however, I found a sketch of an abandoned channel and the words “wet clay after rain.” That apparently marginal observation helped me recognise where the old course had been. The instrument and the notebook did not compete for the honour of being right. One fixed my present position; the other made an earlier position intelligible. Their disagreement had become a way to ask a more accurate question.

[5] This is not an argument for damp paper over reliable electronics. A sensor can keep a patient record of changes that a person visiting once would miss. Digital photographs allow a colleague to inspect details a hurried sketch might omit. Nor should every hesitation be promoted into wisdom: some crossed-out numbers are simply mistakes. The relevant distinction is between an observation and a conclusion that conceals how it was reached. A digital field record can preserve that distinction exceptionally well, provided its designer does not treat uncertainty as a field that ought to be left blank.

[6] I now ask students to record what would make them revise an identification. At first, some regard this as an invitation to sound unprepared. They have learned to associate expertise with an answer delivered without visible friction. Yet “I would change my mind if the layer continued beyond the fault” is more demanding than a decorative admission that anything is possible. It names a test. It also gives the next observer something to do. The notebook becomes less a private certificate of competence and more a set of instructions for a person who may disagree intelligently with its author.

[7] On the final page of that day's notes I redrew the boundary with a short dotted section. The dots did not mean that the ground underneath them lacked a history, or that every account of it was equally good. They meant that this part of my account had earned less confidence than the rest. Months later, another researcher sent a photograph of an exposure revealed by winter weather. We moved the line. The revised map was more useful because the earlier notebook had made revision possible. I trust a careful observer not because the observer never changes a line, but because I can discover what it would take to move one.`;

export const AP_ENGLISH_DRAFT_C = `Writing set C — Draft for a community newsletter
The following unfinished article argues for a small tool-lending collection at the fictional Northbank Library. All local examples and numbers are invented. Sentence numbers are supplied for revision questions.

(1) A ladder can spend fifty weeks in a cupboard while its owner needs an electric drill that sits unused next door. (2) A tool-lending collection would not solve every household problem, but it could make occasional repairs less expensive for Northbank residents. (3) Our library already lends books, so obviously it can lend any object at all without changing how it works. (4) The proposal deserves a trial, provided the library plans for maintenance as carefully as it plans for borrowing.

(5) Under the proposed six-month trial, members would reserve a small selection of hand tools and low-risk equipment through the existing catalogue. (6) A trained assistant would check each item before and after a loan, record damage and explain the return procedure. (7) Instructions would accompany every item in clear print, and demonstrations would be offered at a weekly session. (8) A volunteer who has repaired bicycles for thirty years said that knowing when not to use a tool is sometimes the most useful instruction of all.

(9) Some residents worry that tools will displace books and take staff away from readers who need help. (10) These are practical objections, not evidence that the residents dislike cooperation. (11) The trial would occupy one locked cabinet in the unused storeroom, and its staffing budget would be separate from the reading-room budget. (12) The storeroom was painted green several years ago, although the paint is now quite faded. (13) The council should publish the trial's actual staff hours as well as its number of loans, since a popular collection might still require more support than the library can afford.

(14) Access also depends on rules that appear minor on a form. (15) A large cash deposit could exclude precisely the residents who cannot afford to buy tools, while an online-only reservation system could exclude residents who rarely use the internet. (16) Telephone reservations and a modest, clearly explained replacement policy would address those barriers without pretending that lost equipment costs nothing. (17) At the end of the trial, residents and staff should review both successful loans and the repairs, refusals and delays that do not fit neatly into a publicity photograph. (18) In conclusion, tools are very useful things and libraries have many different kinds of members.`;

export const AP_ENGLISH_DRAFT_D = `Writing set D — Draft opinion article for a town newspaper
The writer is discussing street lighting in the fictional town of Ellerton. The trial, observations and quoted comments are invented for this examination.

(1) When the street outside my flat received brighter lamps, I expected the walk from the bus stop to become easier. (2) Instead, I could see the pavement directly beneath each lamp brilliantly and had trouble seeing into the darker stretch beyond it. (3) My experience alone cannot establish what lighting plan is safest, but it prompted a question the council's proposal barely addresses: where does the light go? (4) Ellerton should test the placement and shielding of its street lights before committing to a town-wide increase in brightness.

(5) A lamp that sends light toward a bedroom window or above the street spends part of its output illuminating places pedestrians do not need to see. (6) Shielding redirects more light toward the intended area, although the result still depends on spacing and the shape of the street. (7) New lamps are always good for the environment because new technology uses less energy. (8) A comparison should therefore measure electricity used by the complete installation, rather than assuming that the efficiency of each lamp settles the matter.

(9) Last winter the council tried shielded lamps on two similar residential streets. (10) Both streets used less electricity than they had in the previous winter, and residents reported fewer complaints about light entering bedrooms. (11) The report did not record changes in traffic, weather or the hours during which the lamps operated. (12) Nor were the two streets chosen at random from all streets in the town. (13) The trial suggests questions worth investigating; it does not yet justify announcing a result for every neighbourhood.

(14) Shopkeepers on the late bus route have raised a different concern. (15) They want customers and staff to feel comfortable waiting outside after closing time, and they fear that any mention of reducing wasted light is a disguised proposal to leave the route dark. (16) The council could invite these users on evening walks with lighting staff, comparing faces, steps and crossing points under several arrangements. (17) The aim would be to discover what people need to distinguish, not to win an argument by making one photograph look brighter than another. (18) After these walks, the council should publish a comparison of visibility, energy use and residents' concerns. (19) A successful lighting plan is not one that makes the town look brightest from a distant hill. (20) It is one that helps the people on its streets see what matters.`;

export const AP_ENGLISH_DRAFT_E = `Writing set E — Draft memo to a school history department
The fictional student writer proposes an oral-history project about the closure of a local factory. All names, events and examples are invented. The memo is unfinished.

(1) Our town's factory closed before most current students were born, but its story still enters conversations about work, housing and the river. (2) The history department should support a student oral-history project that records several accounts of the closure and preserves the conditions under which each account was given. (3) Interviewing residents would supply a complete and unquestionably accurate replacement for the documents we already have. (4) The project would be stronger if interviews and written records were used to question one another.

(5) A retired supervisor might remember the last week through decisions about machinery, while a nearby shopkeeper might remember cancelled orders. (6) A worker who moved away could connect the closure to events outside the town that local residents rarely mention. (7) Such differences need not be removed to make a useful collection. (8) They can reveal how a single event altered people's lives in different ways, although interviewers must still check dates and distinguish recollection from direct observation.

(9) Before recording, students should explain who will hear the interview, where it will be stored and whether the speaker can request restrictions on particular passages. (10) Consent should be treated as an ongoing agreement rather than a signature that ends the conversation. (11) For example, a speaker may become uncomfortable when an apparently ordinary workplace story begins to identify another person. (12) The department will need a procedure for reviewing such requests, because a promise that students cannot keep would damage the trust on which later interviews depend.

(13) Students should begin with open questions that allow a speaker to establish what mattered to them. (14) Follow-up questions can then ask for a specific scene, a date or the reason the speaker interprets an event in a particular way. (15) We should buy the most expensive microphones available, since the price of recording equipment determines the historical value of an interview. (16) A short pilot with borrowed equipment would let students practise listening, checking the recording and writing a description that helps future users understand its context. (17) The pilot should be reviewed before the department promises a large public collection. (18) If we design the process carefully, the finished recordings will preserve not just answers about the factory but evidence of how those answers were shaped in conversation.`;

export const AP_ENGLISH_RHETORIC = `Free response 2 — Welcome to the unfinished rehearsal
The following original simulated speech is attributed to the fictional conductor Leona Faris, welcoming new and returning members of an amateur community orchestra at its first rehearsal after a long closure. The speaker, orchestra and occasion are invented, not a historical source.

[1] Before we begin, I should confess that I practised these opening remarks more often this week than I practised the difficult entrance in tonight's score. That is an unfortunate example for a conductor to set, but perhaps an honest one. We have all been preparing different things for this evening. Some of you have been preparing scales; some have been preparing an explanation to the people at home of why Tuesday nights now belong to a violin case. One person has written to ask whether there is a place here for someone who can still read music but no longer quite trusts the hands that must play it. There is a place. It is not at the back unless that is where you would like to sit.

[2] During the closure I kept our last programme on the piano. At first I treated it as a promise that we would return to exactly the same sound. Then I noticed how much the programme left out. It did not mention the bus that brought two players from the other side of town, the neighbour who watched a child, or the patient person who repaired a borrowed bow. It named the music and the musicians. It did not name all the work that allowed the music to happen. Tonight, returning is an opportunity to hear that quieter work and to share it more fairly.

[3] We are not going to pretend that everyone arrives with the same experience. A beginner does not need to be told that a difficult passage is easy; an experienced player does not need to apologise for having learned it. What we can promise is that difficulty will not become a private embarrassment. Ask for the rhythm again. Mark the passage you cannot yet follow. If you have mastered it, play it slowly enough for someone beside you to find the way in. Generosity does not lower the standard. It changes how we reach it.

[4] You will hear a wrong note this evening. You may even hear one from the conductor's keyboard. A wrong note is information: the finger arrived early, the eye lost its place, the breath ran short. What matters next is whether the room makes that information usable. Laughter that welcomes an attempt can release a whole section's shoulders. Laughter that assigns someone the role of permanent beginner can silence that person for months. I cannot print the difference as a rule on the music stand, but every one of us can help the person next to us feel it.

[5] There are practical promises behind this welcome. We have set aside the first fifteen minutes before each rehearsal for anyone who wants to try a passage in a smaller group. The instrument fund will remain anonymous, because borrowing a cello should not require performing gratitude in public. We will rotate some seating positions, not to pretend that experience is irrelevant, but to make sure that advice and responsibility do not travel in only one direction. If one of these arrangements makes participation harder for you, tell us. A policy can sound generous from the podium and still put a staircase in somebody's path.

[6] Our concert will have an audience, and we owe that audience careful work. I would not ask you to spend these evenings producing a performance that we excuse in advance. But applause cannot be our only evidence of success. Listen for the returning player who stops apologising before every entrance. Listen for the experienced player who discovers a better way to explain a phrase. Listen for the rest that everyone keeps together: a moment in which nobody is displaying a note and everybody is making music possible. Those achievements are not alternatives to a good concert. They are part of its construction.

[7] So let us begin with the passage that none of us quite likes. We could save it until we feel more certain of one another, but certainty is not the admission ticket to this room. It is something we may build here, by returning, by listening, by making an honest attempt that leaves room for another person's attempt. Open the score. Leave space on the stand. We have a great deal to practise, and at last we have people with whom to practise it.`;
