import { pearsonMock, type PearsonItem } from "./pearson-common.ts";

const common: PearsonItem[] = [
  ["Discount and original price", 5,
    "A tablet sells for $276 after a reduction of 8%. (a) Find the original price. [3] (b) A shop buys one at $240 and sells it for $276. Find the percentage profit on the buying price. [2]",
    "(a) M1:276 is92% of original; M1:276/0.92; A1:$300. (b) M1:(276−240)/240×100; A1:15%."],
  ["Simultaneous equations", 5,
    "(a) Solve 4x + 3y = 29 and 2x − y = 7. [4] (b) Find 3x − 2y using your solution. [1]",
    "(a) M1:second equation×3 or expressy=2x−7; M1:10x=50; A1:x=5; A1:y=3. (b) B1:9."],
  ["Arithmetic sequence", 5,
    "An arithmetic sequence begins 11, 17, 23, 29. (a) Find the nth term. [2] (b) Find the 30th term. [1] (c) Show that 202 is not a term. [2]",
    "(a) M1:coefficient6; A1:6n+5. (b) B1:185. (c) M1:6n+5=202 givesn=197/6; A1:not an integer, hence not a term."],
  ["Changing the subject", 5,
    "(a) Make x the subject of y = 5x − 7. [2] (b) Make h the subject of A = ½(a + b)h. [2] (c) Use your formula to find h when A = 54, a = 7 and b = 11. [1]",
    "(a) M1:y+7=5x; A1:x=(y+7)/5. (b) M1:2A=(a+b)h; A1:h=2A/(a+b). (c) B1:6."],
  ["Standard form in context", 5,
    "A file contains 3.2 × 10⁸ bytes. (a) Write this as an ordinary number. [1] (b) A device stores 7.5 × 10¹¹ bytes. Find the greatest whole number of these files that it can store. [3] (c) Write the total size of 25 files in standard form. [1]",
    "(a) B1:320000000. (b) M1:(7.5×10¹¹)/(3.2×10⁸); M1:2343.75; A1:2343 complete files. (c) B1:8×10⁹ bytes."],
  ["Triangular prism", 5,
    "A right prism has a right-triangle cross-section with perpendicular sides 6 cm and 8 cm. The prism is 15 cm long. (a) Find its volume. [2] (b) Find its total surface area. [3]",
    "(a) M1:cross-section½×6×8=24; A1:360 cm³. (b) M1:hypotenuse10; M1:2×24+15(6+8+10); A1:408 cm²."],
  ["Transformation and similarity", 5,
    "Triangle A has vertices (1,2), (3,2), (1,5). (a) Enlarge it by scale factor 2, centre the origin, and give all image coordinates. [2] (b) Reflect the original triangle in the line y = x and give its image coordinates. [2] (c) Explain which of these two images is congruent to the original. [1]",
    "(a) M1:double both coordinates; A1:(2,4),(6,4),(2,10). (b) M1:swap coordinates; A1:(2,1),(2,3),(5,1). (c) B1:reflected triangle; reflection preserves lengths while enlargement scale2 does not."],
  ["Grouped mass data", 5,
    "Forty parcels have masses m kg grouped as follows: 0 < m ≤ 2: 8; 2 < m ≤ 4: 15; 4 < m ≤ 6: 11; 6 < m ≤ 8: 6. (a) State the modal class. [1] (b) Estimate the mean mass. [3] (c) Explain why this mean is an estimate. [1]",
    "(a) B1:2<m≤4. (b) M1:midpoints1,3,5,7; M1:weighted sum8+45+55+42=150 divided by40; A1:3.75 kg. (c) B1:exact individual masses unknown, assumed at midpoints."],
];

const foundation: PearsonItem[] = [
  ["Ratio", 4,
    "(a) Simplify the ratio 36:60. [1] (b) Share 480 ml in the ratio 3:5. [3]",
    "(a) B1:3:5. (b) M1:8 parts,60 ml each; A1:180 ml; A1:300 ml."],
  ["Percentage skills", 4,
    "(a) Write 7/20 as a percentage. [1] (b) Find 12% of 350. [1] (c) A price rises from $80 to $92. Find the percentage increase. [2]",
    "(a) B1:35%. (b) B1:42. (c) M1:(92−80)/80×100; A1:15%."],
  ["Standard form", 4,
    "(a) Write 5600000 in standard form. [1] (b) Write 4.8 × 10⁻³ as a decimal. [1] (c) Calculate (3 × 10⁵)(2 × 10⁻²), giving standard form. [2]",
    "B1:5.6×10⁶; B1:0.0048. (c) M1:multiply coefficients,add powers; A1:6×10³."],
  ["Inequality", 4,
    "(a) Solve 4x − 3 ≤ 17. [2] (b) Show the answer on a number line. [1] (c) List the positive integer solutions. [1]",
    "(a) M1:4x≤20; A1:x≤5. (b) B1:closed circle5,ray left. (c) B1:1,2,3,4,5."],
  ["Formulae", 4,
    "A delivery charge is given by C = 6 + 2d, where d is distance in kilometres and C is dollars. (a) Find C when d = 9. [1] (b) Make d the subject. [2] (c) Find d when C = 31. [1]",
    "(a) B1:24. (b) M1:C−6=2d; A1:d=(C−6)/2. (c) B1:12.5 km."],
  ["Sequences", 5,
    "(a) A sequence begins 2, 6, 18, 54. Write the next two terms and state its term-to-term rule. [2] (b) Another sequence has nth term 4n − 1. Find its first three terms. [1] (c) Find the position of 99 in the second sequence. [2]",
    "(a) B1:162,486; B1:multiply by3. (b) B1:3,7,11. (c) M1:4n−1=99; A1:n=25."],
  ["Costs and equations", 5,
    "Two sandwiches and one drink cost $11. One sandwich and two drinks cost $10. (a) Write two equations. [2] (b) Find the price of a sandwich and a drink. [3]",
    "(a) B1 each:2s+d=11,s+2d=10. (b) M1:eliminate variable; A1:s=4; A1:d=3."],
  ["Simple interest", 5,
    "(a) $1500 earns simple interest at 4% per year for 3 years. Find the total interest and the final balance. [3] (b) A different account pays total simple interest of $210 on $1500 over 2 years. Find its annual percentage rate. [2]",
    "(a) M1:1500×0.04×3; A1:interest$180; A1:balance$1680. (b) M1:210/(1500×2)×100; A1:7%."],
  ["Polygons and symmetry", 5,
    "(a) Find one interior angle of a regular decagon. [2] (b) Find the number of sides of a regular polygon whose exterior angle is 24°. [2] (c) State the order of rotational symmetry of a non-square rectangle. [1]",
    "(a) M1:180−360/10; A1:144°. (b) M1:360/24; A1:15. (c) B1:2."],
  ["Scale plan and bisector", 5,
    "On a plan, A = (0,0) and B = (8,0), with one coordinate unit representing 10 m. (a) Draw AB on a square grid and mark its midpoint M. [1] (b) Draw the perpendicular bisector of AB and state its equation. [2] (c) A point C is at (4,3). Find its actual distance from A. [2]",
    "(a) B1:AB correctly drawn,M=(4,0). (b) M1:perpendicular line through midpoint; A1:x=4. (c) M1:√(4²+3²)×10; A1:50 m. This tests the bisector's geometry; it does not certify compass-construction accuracy."],
  ["Cylinder capacity", 5,
    "A closed cylinder has radius 3 cm and height 10 cm. (a) Find its volume in cm³. [2] (b) Find its total surface area. [3]",
    "(a) M1:π×3²×10; A1:90π≈283 cm³. (b) M1:curved60π; M1:add2×9π; A1:78π≈245 cm²."],
  ["Averages", 3,
    "The values are 5, 6, 6, 8, 10. (a) Find the mode. [1] (b) Find the median. [1] (c) Find the range. [1]",
    "B1 each:6;6;5."],
  ["Pie chart", 3,
    "A club has 40 members: 10 choose tennis, 15 badminton, 5 squash and 10 table tennis. (a) Calculate the pie-chart angle for badminton. [2] (b) State the fraction choosing squash. [1]",
    "(a) M1:15/40×360; A1:135°. (b) B1:1/8."],
  ["Missing score", 4,
    "(a) Four test scores have a mean of 12. Find their total. [1] (b) Three of them are 9, 14 and 11. Find the fourth. [1] (c) A fifth score of 17 is added. Calculate the new mean. [2]",
    "(a) B1:48. (b) B1:14. (c) M1:(48+17)/5; A1:13."],
];

const higher: PearsonItem[] = [
  ["Algebraic proof", 4,
    "Prove that the sum of three consecutive integers is divisible by 3. Then show that the sum of their squares is 2 more than a multiple of 3. [4]",
    "M1:integersn−1,n,n+1; A1:sum3n hence divisible by3; M1:squares(n−1)²+n²+(n+1)²=3n²+2; A1:3n² is a multiple of3, remainder2."],
  ["Inverse proportion", 4,
    "The time T hours to complete a fixed task is inversely proportional to the number n of identical machines. With 6 machines, T = 15. (a) Find T in terms of n. [2] (b) Find the least whole number of machines needed to finish in at most 8 hours. [2]",
    "(a) M1:T=k/n,k=90; A1:T=90/n. (b) M1:90/n≤8 givesn≥11.25; A1:12 machines."],
  ["Functions", 4,
    "f(x) = 2x + 1 and g(x) = (x − 3)². (a) Find fg(x). [1] (b) Find f⁻¹(x). [2] (c) Solve gf(x) = 0. [1]",
    "(a) B1:2(x−3)²+1. (b) M1:rearrangey=2x+1; A1:(x−1)/2. (c) B1:(2x−2)²=0 givesx=1."],
  ["Inequality region", 4,
    "On coordinate axes, show the region satisfying x ≥ 0, y ≥ 0, x + y ≤ 6 and y ≤ 2x. State the coordinates of its vertices. [4]",
    "B1:axes with first-quadrant restriction; B1:boundariesx+y=6 andy=2x correctly drawn; B1:correct closed triangular region; B1:vertices(0,0),(6,0),(2,4)."],
  ["Arithmetic series", 4,
    "An arithmetic sequence has fourth term 17 and tenth term 41. (a) Find its first term and common difference. [2] (b) Find the sum of its first 25 terms. [2]",
    "(a) M1:d=(41−17)/(10−4)=4; A1:a=5. (b) M1:25/2[2×5+24×4]; A1:1325."],
  ["Stationary points", 5,
    "For y = x³ − 3x² − 9x + 4, find the stationary points and classify each using the signs of the gradient on either side. [5]",
    "M1:dy/dx=3x²−6x−9; M1:3(x−3)(x+1)=0; A1:points(−1,9),(3,−23); B1:+to− at−1,maximum; B1:−to+ at3,minimum."],
  ["Kinematics", 5,
    "A particle's displacement from O is s = t³ − 6t² + 12t metres, where t is time in seconds and 0 ≤ t ≤ 5. (a) Find its velocity and acceleration as functions of t. [2] (b) Find the time at which it is instantaneously at rest. [1] (c) Does it reverse direction at that time? Explain. [2]",
    "(a) B1:v=3t²−12t+12; B1:a=6t−12. (b) B1:t=2. (c) M1:v=3(t−2)² is positive on both sides of2; A1:no change of velocity sign, so no reversal."],
  ["Nonlinear simultaneous equations", 5,
    "Solve x² + y² = 25 and y = x + 1, giving both pairs of coordinates. [5]",
    "M1:substitutex²+(x+1)²=25; M1:2x²+2x−24=0; M1:(x+4)(x−3)=0; A1:x=−4,3; A1:paired(−4,−3),(3,4)."],
  ["Cone and sphere", 5,
    "A solid metal cone of radius 6 cm and height 12 cm is melted without loss and cast into spheres of radius 2 cm. (a) Find the cone volume in terms of π. [2] (b) Find the volume of one sphere in terms of π. [1] (c) Find the number of complete spheres and the unused volume. [2]",
    "(a) M1:π×6²×12/3; A1:144π cm³. (b) B1:32π/3 cm³. (c) M1:144π/(32π/3)=13.5; A1:13 complete spheres with16π/3 cm³ unused, both required."],
  ["Intersecting chords", 5,
    "Chords AB and CD intersect inside a circle at P. AP = 3 cm, PB = 8 cm and CP = 4 cm. (a) Find PD. [2] (b) A different circle has centre O and a chord EF of length 16 cm. The perpendicular distance from O to EF is 6 cm. Find the radius, explaining the circle property used. [3]",
    "(a) M1:AP×PB=CP×PD; A1:PD=6 cm. (b) B1:perpendicular from centre bisects chord,half8; M1:r²=8²+6²; A1:r=10 cm."],
  ["Vector proof", 5,
    "In triangle OAB, OA = a and OB = b. P divides OA in the ratio OP:PA = 2:1 and Q divides OB in the ratio OQ:QB = 2:1. (a) Express PQ in terms of a and b. [2] (b) Prove that PQ is parallel to AB and state PQ:AB. [2] (c) Find the position vector of the midpoint of PQ. [1]",
    "(a) M1:OQ−OP; A1:(2/3)(b−a). (b) M1:AB=b−a andPQ is positive scalar multiple; A1:parallel,ratio2:3. (c) B1:(a+b)/3."],
  ["Quartiles", 3,
    "The ordered data are 2, 4, 6, 7, 9, 11, 14, 16, 18. Exclude the overall median when taking the medians of the two halves. Find the lower quartile, upper quartile and interquartile range. [3]",
    "B1 each:Q1=5;Q3=15;IQR=10."],
  ["Cumulative frequency", 3,
    "For 60 times, cumulative frequencies at 0, 10, 20, 30, 40 minutes are 0, 8, 26, 50, 60. (a) Draw a cumulative-frequency graph. [2] (b) Estimate the median using straight-line interpolation between successive points. [1]",
    "(a) B1:labelled axes and five correct points; B1:increasing joined graph. (b) B1:20+(30−26)/24×10=21.67 minutes; accept21.3–22.0 from the graph."],
  ["Comparing distributions", 4,
    "Group A has minimum 12, lower quartile 18, median 25, upper quartile 31 and maximum 42. Group B has minimum 9, lower quartile 20, median 23, upper quartile 27 and maximum 48. (a) Calculate both interquartile ranges. [2] (b) Compare the typical values and the spread of the middle halves. [2]",
    "(a) B1 each:A IQR13;B IQR7. (b) B1:A higher median25 versus23; B1:B more consistent middle half, IQR7 versus13. Range comparison alone is not the requested middle-half comparison."],
];

export const PEARSON_MODULAR_TWO = [
  pearsonMock("Unit 2 (4WM2F/01)", "Foundation", true, [...foundation, ...common]),
  pearsonMock("Unit 2 (4WM2H/01)", "Higher", true, [...common, ...higher]),
];
