import { pearsonMock, type PearsonItem } from "./pearson-common.ts";

// 40 common marks: number/algebra 25, geometry 10, handling data 5.
const common: PearsonItem[] = [
  ["Recipe and scale", 5,
    "Flour, oats and seeds are mixed in the ratio 5:3:2. A batch contains 360 g of oats. (a) Find the total mass of the batch. [2] (b) Find the mass of seeds. [1] (c) A new batch has total mass 1.8 kg. Find the extra flour needed compared with the first batch. [2]",
    "(a) M1: 360÷3 = 120 g per part; A1: 1200 g. (b) B1: 240 g. (c) M1: new flour = 1800×5/10 = 900 g and old flour = 600 g; A1: extra 300 g."],
  ["Ticket equations", 5,
    "A museum charges one price for an adult ticket and one price for a child ticket. Two adult tickets and three child tickets cost $39. Three adult tickets and two child tickets cost $46. (a) Form two equations. [2] (b) Find each ticket price. [3]",
    "(a) B1 each: 2a+3c=39 and 3a+2c=46. (b) M1: valid elimination/substitution, e.g. 9a+6c=138 minus 4a+6c=78; A1: a=12; A1: c=5."],
  ["Quadratic model", 5,
    "A rectangle has width x cm and length (x + 5) cm. Its area is 84 cm². (a) Form an equation in x. [1] (b) Solve your equation and explain which solution is possible. [3] (c) Find the perimeter. [1]",
    "(a) B1: x(x+5)=84. (b) M1: (x+12)(x−7)=0; A1: roots 7 and −12; B1: reject −12 because length is positive, so x=7. (c) B1: 38 cm."],
  ["Coordinate graph", 5,
    "The line L has equation y = 3x − 4. (a) Complete a table for x = −1, 0, 1, 2. [2] (b) Plot these points and draw L on labelled axes. [2] (c) State the gradient of L. [1]",
    "(a) B1 for two/three correct values; B2 for −7,−4,−1,2. (b) B1: suitable labelled axes and accurate points; B1: straight line through the points. (c) B1: 3."],
  ["Percentage comparison", 5,
    "A bicycle marked at $480 is reduced by 15%. (a) Calculate the sale price. [2] (b) A different shop sells the same bicycle for $420. Find the percentage by which its price exceeds the sale price. [3]",
    "(a) M1: 480×0.85; A1: $408. (b) M1: difference 12; M1: 12/408×100; A1: 2.94%. Denominator must be the sale price."],
  ["Ramp geometry", 5,
    "A straight ramp rises 0.9 m over a horizontal distance of 4.8 m. (a) Find its sloping length. [3] (b) Find its angle to the horizontal, to 1 decimal place. [2]",
    "(a) M1: L²=4.8²+0.9²; M1: square root of 23.85; A1: 4.88 m. (b) M1: tan θ=0.9/4.8; A1: 10.6°."],
  ["Cylinder container", 5,
    "An open-top cylindrical container has internal radius 4 cm and height 12 cm. Ignore thickness. (a) Calculate its capacity in millilitres. [2] (b) Find the area of material forming its curved wall and single circular base. [3]",
    "(a) M1: π×4²×12; A1: 192π = 603 ml (1 cm³=1 ml). (b) M1: wall 2π×4×12; M1: add one base π×4²; A1: 112π = 352 cm²."],
  ["Grouped travel times", 5,
    "Travel times t minutes for 30 students are grouped as follows: 0 < t ≤ 10: 4; 10 < t ≤ 20: 12; 20 < t ≤ 30: 9; 30 < t ≤ 40: 5. (a) State the modal class. [1] (b) Estimate the mean time. [3] (c) Explain why the exact mean cannot be found from these data. [1]",
    "(a) B1: 10<t≤20. (b) M1: midpoints 5,15,25,35; M1: weighted sum 600 divided by 30; A1: 20 minutes. (c) B1: individual times are unknown within each class."],
];

const foundation: PearsonItem[] = [
  ["Number skills", 4,
    "(a) Write 6047 in words. [1] (b) Calculate 38 × 24. [1] (c) Put −2, 0.7, −0.5, 0 in ascending order. [1] (d) Round 7.846 to 2 decimal places. [1]",
    "B1 each: six thousand and forty-seven; 912; −2,−0.5,0,0.7; 7.85."],
  ["Fractions", 4,
    "(a) Write 18/24 in simplest form. [1] (b) Calculate 5/6 − 1/4. [2] (c) Find 3/5 of 140. [1]",
    "(a) B1: 3/4. (b) M1: common denominator 12, 10/12−3/12; A1: 7/12. (c) B1: 84."],
  ["Shopping", 4,
    "A notebook costs $2.35 and a pen costs $1.60. (a) Find the cost of 4 notebooks and 3 pens. [2] (b) A customer pays with $20. Find the change. [1] (c) Pens are also sold in packs of 5 for $7.25. Find the saving per pen compared with buying one pen. [1]",
    "(a) M1: 4×2.35+3×1.60; A1: $14.20. (b) B1: $5.80. (c) B1: $0.15 (pack unit price $1.45)."],
  ["Algebra expressions", 4,
    "(a) Simplify 5a + 3b − 2a + b. [1] (b) Expand 4(2x − 3). [1] (c) Factorise 6y + 15. [1] (d) Find 2p² − q when p = −3 and q = 5. [1]",
    "B1 each: 3a+4b; 8x−12; 3(2y+5); 13."],
  ["Powers and factors", 4,
    "(a) Express 84 as a product of prime factors. [2] (b) Find the highest common factor of 84 and 126. [1] (c) Calculate √169 + 2³. [1]",
    "(a) M1: factor tree/division into primes; A1: 2²×3×7. (b) B1: 42. (c) B1: 21."],
  ["Number patterns", 5,
    "A sequence begins 7, 11, 15, 19. (a) Write the next two terms. [1] (b) Write an expression for the nth term. [2] (c) Is 103 a term? Explain using your expression. [2]",
    "(a) B1: 23,27. (b) M1: coefficient 4; A1: 4n+3. (c) M1: solve 4n+3=103 giving n=25; A1: yes, the 25th term."],
  ["Equations and inequality", 5,
    "(a) Solve 5x − 7 = 28. [2] (b) Solve 3(y + 2) = 24. [2] (c) List all integer values of n satisfying −2 < n ≤ 2. [1]",
    "(a) M1: 5x=35; A1: x=7. (b) M1: y+2=8 or 3y+6=24; A1: y=6. (c) B1: −1,0,1,2."],
  ["Standard form and estimates", 5,
    "(a) Write 0.00072 in standard form. [1] (b) Write 3.5 × 10⁵ as an ordinary number. [1] (c) Calculate (6 × 10⁴) ÷ (2.5 × 10²), giving standard form. [2] (d) Estimate 19.8 × 5.1 by rounding each number to 1 significant figure. [1]",
    "B1: 7.2×10⁻⁴; B1: 350000. (c) M1: 2.4×10^(4−2); A1: 2.4×10². (d) B1: 20×5=100."],
  ["Angles", 5,
    "In triangle ABC, AB = AC and angle BAC = 44°. (a) Find angle ABC, giving a reason. [2] (b) BC is extended beyond C to D. Find angle ACD. [1] (c) A regular polygon has exterior angle 30°. Find its number of sides and one interior angle. [2]",
    "(a) M1: equal base angles and triangle sum; A1: 68°. (b) B1: 112°. (c) B1 each: 12 sides; 150°."],
  ["Garden plan", 5,
    "A rectangular garden is 12 m by 8 m. A rectangular pond 3 m by 2 m lies completely inside it. (a) Find the garden's perimeter. [1] (b) Find the remaining area. [2] (c) Grass seed covers 15 m² per bag. Find the smallest number of bags needed for the remaining area. [2]",
    "(a) B1: 40 m. (b) M1: 12×8−3×2; A1: 90 m². (c) M1: 90/15; A1: 6 bags."],
  ["Transformation", 5,
    "Triangle T has vertices A(1,1), B(4,1), C(1,3). (a) Draw T on coordinate axes. [1] (b) Reflect T in the y-axis and state all image coordinates. [2] (c) Instead translate the original T by the column vector (−2, 3). State the image of A and explain whether its area changes. [2]",
    "(a) B1: correctly joined plotted triangle. (b) B1 for x signs reversed; A1 all: (−1,1),(−4,1),(−1,3). (c) B1: (−1,4); B1: area unchanged because translation preserves lengths/shape."],
  ["Averages", 3,
    "Six scores are 4, 7, 7, 8, 9, 13. (a) Find the mode. [1] (b) Find the median. [1] (c) Find the mean. [1]",
    "B1 each: 7; 7.5; 8 (sum48/6)."],
  ["Probability", 3,
    "A bag holds 5 red, 3 blue and 2 white counters. One is selected at random. (a) Find P(blue). [1] (b) Find P(not white). [1] (c) Over 200 selections with replacement, estimate the number of red selections. [1]",
    "B1 each: 3/10; 8/10=4/5; 100."],
  ["Frequency chart", 4,
    "Twenty-four students choose one activity: art 6, chess 8, music 4, sport 6. (a) Draw a labelled bar chart. [2] (b) Calculate the angle for chess in a pie chart. [2]",
    "(a) B1: labelled axes and consistent frequency scale; B1: all four bars correct heights and separated. (b) M1: 8/24×360; A1: 120°."],
];

const higher: PearsonItem[] = [
  ["Surds and indices", 4,
    "(a) Simplify √75 − √12. [2] (b) Evaluate 81^(3/4). [1] (c) Simplify x⁵x⁻²/x, where x ≠ 0. [1]",
    "(a) M1: 5√3−2√3; A1: 3√3. (b) B1: 27. (c) B1: x²."],
  ["Algebraic fractions", 4,
    "(a) Simplify (x² − 9)/(x² + x − 6), stating excluded x values in the original expression. [3] (b) Solve (x − 3)/(x − 2) = 2. [1]",
    "(a) M1: numerator (x−3)(x+3) and denominator (x+3)(x−2); A1: (x−3)/(x−2); B1: x≠−3,2. (b) B1: x=1."],
  ["Bounds", 4,
    "A distance is 18.6 km to the nearest 0.1 km. A time is 24 minutes to the nearest minute. Find the lower and upper bounds of average speed in km/h. Show the values used in each calculation. [4]",
    "M1: distance bounds18.55,18.65; M1: time bounds23.5/60,24.5/60 h; A1: lower18.55×60/24.5=45.42857… km/h; A1: upper18.65×60/23.5=47.61702… km/h. Accept exact fractions or adequate precision."],
  ["Functions", 4,
    "f(x) = 3x − 2 and g(x) = x² + 1. (a) Find gf(2). [1] (b) Find f⁻¹(x). [2] (c) Solve g(x) = 10. [1]",
    "(a) B1: g(4)=17. (b) M1: y=3x−2 rearranged; A1: (x+2)/3. (c) B1: x=±3, both required."],
  ["Arithmetic series", 4,
    "An arithmetic sequence has first term 9 and common difference 4. (a) Find its 20th term. [1] (b) Find the sum of its first 20 terms. [2] (c) Explain why no term is divisible by 4. [1]",
    "(a) B1: 85. (b) M1: 20/2×(9+85); A1: 940. (c) B1: term4n+5 leaves remainder1 modulo4."],
  ["Quadratic intersections", 5,
    "The curve y = x² − 4x + 1 meets the line y = 2x − 4. Find both intersection points, giving coordinates in exact form. [5]",
    "M1: x²−6x+5=0; M1: (x−1)(x−5)=0; A1: x=1,5; A1: y=−2,6; A1: paired points (1,−2),(5,6)."],
  ["Calculus and tangent", 5,
    "A curve has equation y = x³ − 3x² + 2. (a) Find dy/dx. [2] (b) Find the gradient at x = 2. [1] (c) Find the equation of the tangent at x = 1. [2]",
    "(a) B1 each: 3x² and −6x. (b) B1: 0. (c) M1: point(1,0), gradient−3; A1: y=−3x+3."],
  ["Repeated percentage and proof", 5,
    "(a) A machine worth $18000 depreciates by 12% each year. Find its value after 3 years, to the nearest dollar. [2] (b) Prove that the difference between the squares of any two consecutive odd positive integers is divisible by 8. [3]",
    "(a) M1:18000×0.88³; A1:$12266. (b) M1: integers2n+1 and2n+3; M1: difference(2n+3)²−(2n+1)²=8n+8; A1:8(n+1), integer multiple of8."],
  ["Non-right triangle", 5,
    "Triangle ABC has AB = 9 cm, AC = 12 cm and angle BAC = 58°. (a) Find BC. [3] (b) Find the area of ABC. [2]",
    "(a) M1: BC²=9²+12²−2×9×12cos58°; M1: square root; A1:10.5 cm (10.514…). (b) M1:½×9×12sin58°; A1:45.8 cm²."],
  ["Similarity and volume", 5,
    "Two mathematically similar solid ornaments have surface areas 72 cm² and 162 cm². The smaller has volume 80 cm³. (a) Find the linear scale factor from smaller to larger. [2] (b) Find the larger volume. [2] (c) The smaller height is 6 cm. Find the larger height. [1]",
    "(a) M1:√(162/72); A1:1.5. (b) M1:80×1.5³; A1:270 cm³. (c) B1:9 cm."],
  ["Vector proof", 5,
    "In triangle OAB, OA = a and OB = b. M is the midpoint of OA. N is the point on AB with AN:NB = 1:2. (a) Express ON in terms of a and b. [2] (b) Express MN in terms of a and b. [2] (c) Is MN parallel to OB? Justify your answer. [1]",
    "(a) M1: a+(b−a)/3; A1:(2a+b)/3. (b) M1:subtract a/2; A1:a/6+b/3. (c) B1:no, nonzero a component; a,b independent for a nondegenerate triangle."],
  ["Conditional probability", 3,
    "A bag has 4 red and 6 blue balls. Two are drawn without replacement. Find the probability that the second is red given that the two balls have different colours. [3]",
    "M1: P(BR)=6/10×4/9=24/90; M1:P(different)=48/90; A1:conditional24/48=1/2."],
  ["Histogram", 3,
    "A histogram represents masses m g. The class 10 < m ≤ 20 has frequency 8. The class 20 < m ≤ 45 has frequency 30. (a) Find both frequency densities. [2] (b) Explain why the second bar is not 30/8 times as high as the first. [1]",
    "B1 each:0.8 and1.2. B1:unequal class widths mean heights encode density, not frequency (height ratio1.5)."],
  ["Cumulative frequency", 4,
    "For 80 waiting times, cumulative frequencies at 0, 10, 20, 30, 40 minutes are 0, 12, 36, 64, 80. (a) Plot a cumulative-frequency graph. [2] (b) Estimate the median and interquartile range by straight-line interpolation between plotted points. [2]",
    "(a) B1: labelled axes and five points; B1: increasing joined graph. (b) B1:median21.43 minutes; B1:IQR=28.57−13.33=15.24 minutes. Accept reading tolerance±0.5 min; both quartiles correspond to CF20 and60."],
];

export const PEARSON_LINEAR_ONE = [
  pearsonMock("Paper 1F", "Foundation", false, [...foundation, ...common]),
  pearsonMock("Paper 1H", "Higher", false, [...common, ...higher]),
];
